#!/usr/bin/env python3
"""Ajoute 7 cartes supplémentaires par chapitre (~15 cartes/chapitre au total)."""
import json

EXTRA = [
  # ═══════════════════════════════════════════════════════════════════════
  # HISTOIRE-GÉO
  # ═══════════════════════════════════════════════════════════════════════
  {"deck":"histoire","id":"h1i","chapitre":"La Première Guerre mondiale","q":"Qu'est-ce que le front d'Orient et les Dardanelles ?","a":"Tentative alliée d'ouvrir un front secondaire contre l'Autriche via les Balkans et de ravitailler la Russie. Campagne de Gallipoli (1915) : échec cuisant allié face aux Ottomans. Le front d'Orient (Salonique) reste secondaire mais mobilise des troupes qui manquent ailleurs."},
  {"deck":"histoire","id":"h1j","chapitre":"La Première Guerre mondiale","q":"Qu'est-ce que la mutinerie de 1917 dans l'armée française ?","a":"Après l'échec sanglant du Chemin des Dames (Nivelle, avr. 1917), des soldats refusent de monter en ligne. ~40 000 mutins. Pétain rétablit le moral : meilleures conditions, permissions, fin des offensives suicidaires. 49 exécutions (dont des fusillés pour l'exemple)."},
  {"deck":"histoire","id":"h1k","chapitre":"La Première Guerre mondiale","q":"Quel rôle jouent les colonies dans la 1GM ?","a":"La France mobilise ~600 000 soldats des colonies (tirailleurs sénégalais, spahis, soldats indochinois…). L'Algérie fournit 170 000 hommes. Les colonies fournissent aussi matières premières et main-d'œuvre pour les usines. En échange, des promesses d'émancipation souvent non tenues."},
  {"deck":"histoire","id":"h1l","chapitre":"La Première Guerre mondiale","q":"Qu'est-ce que les 14 points de Wilson (1918) ?","a":"Programme de paix du président américain Woodrow Wilson (janvier 1918) : liberté des mers, autodétermination des peuples, transparence des traités, réduction des armements, création de la SDN. Inspire les traités de paix mais est largement trahi dans la pratique (Versailles)."},
  {"deck":"histoire","id":"h1m","chapitre":"La Première Guerre mondiale","q":"Qu'est-ce que la SDN (Société des Nations) et pourquoi a-t-elle échoué ?","a":"Créée en 1920 (traité de Versailles) pour maintenir la paix par la coopération internationale. Limites : les USA n'en font pas partie (Sénat refuse), absence de force militaire propre, décisions à l'unanimité. Impuissante face aux agressions japonaise (1931), italienne (1935), allemande (1938)."},
  {"deck":"histoire","id":"h1n","chapitre":"La Première Guerre mondiale","q":"Comment le conflit s'étend-il au-delà de l'Europe ?","a":"Front moyen-oriental (Palestine, Mésopotamie vs Ottomans). Guerre sous-marine dans l'Atlantique (coulage des navires alliés). Colonies africaines impliquées (Cameroun, Togo, Afrique du Sud-Ouest allemand). L'entrée des USA (1917) internationalise définitivement le conflit."},
  {"deck":"histoire","id":"h1o","chapitre":"La Première Guerre mondiale","q":"Qu'est-ce que le génocide arménien (1915) et son lien avec la 1GM ?","a":"Pendant la 1GM, l'Empire ottoman organise la déportation et le massacre systématique des Arméniens chrétiens (accusés de complicité avec la Russie). ~1,2 million de morts. Premier génocide du XXe s. Profite du chaos de la guerre. Reconnu par de nombreux États mais pas par la Turquie."},

  {"deck":"histoire","id":"h2i","chapitre":"Les régimes totalitaires","q":"Qu'est-ce que la crise économique de 1929 et son impact politique en Europe ?","a":"Krach boursier de Wall Street (octobre 1929) → faillites bancaires, chômage massif (6 millions en Allemagne). Délégitimise les démocraties libérales. Favorise la montée des extrêmes : nazisme en Allemagne, fascisme en Europe centrale. L'URSS paraît immunisée (économie planifiée)."},
  {"deck":"histoire","id":"h2j","chapitre":"Les régimes totalitaires","q":"Qu'est-ce que la propagande nazie et ses outils ?","a":"Goebbels, ministre de la propagande : contrôle total des médias (radio, presse, cinéma). Leni Riefenstahl (Triomphe de la volonté). Rassemblements de Nuremberg (mises en scène grandioses). Livres brûlés. Jeunesse hitlérienne. Objectif : créer un peuple uni autour du Führer."},
  {"deck":"histoire","id":"h2k","chapitre":"Les régimes totalitaires","q":"Qu'est-ce que le Goulag soviétique ?","a":"Réseau de camps de travail forcé en URSS (surtout en Sibérie). ~18 millions de détenus sous Staline. Condamnés pour « crimes contre l'État » (opposition réelle ou supposée). Mortalité élevée : froid, malnutrition, travail épuisant. Soljenitsyne (L'Archipel du Goulag, 1973) le révèle à l'Ouest."},
  {"deck":"histoire","id":"h2l","chapitre":"Les régimes totalitaires","q":"Qu'est-ce que la politique étrangère agressive de Hitler avant 1939 ?","a":"Remilitarisation de la Rhénanie (1936), Anschluss (annexion de l'Autriche, mars 1938), annexion des Sudètes (accords de Munich, sept. 1938), occupation de la Tchécoslovaquie (mars 1939). Chaque fois, les démocraties cèdent (politique d'apaisement) encourageant Hitler à aller plus loin."},
  {"deck":"histoire","id":"h2m","chapitre":"Les régimes totalitaires","q":"Quelles sont les différences entre nazisme et fascisme ?","a":"Points communs : parti unique, chef, violence, anti-communisme. Différences : le nazisme est fondé sur le racisme biologique (élimination physique des Juifs et Roms) ; le fascisme mussolinien n'est pas racialement antisémite au départ (lois raciales tardives, 1938 sous pression nazie). L'État prime sur la race chez Mussolini."},
  {"deck":"histoire","id":"h2n","chapitre":"Les régimes totalitaires","q":"Qu'est-ce que le pacte germano-soviétique (août 1939) ?","a":"Traité de non-agression signé le 23 août 1939 entre Hitler (Ribbentrop) et Staline (Molotov). Protocole secret : partage de la Pologne, zones d'influence en Europe de l'Est. Stupéfaction mondiale (idéologies opposées). Libère Hitler d'une guerre sur deux fronts. Rompu par Hitler le 22 juin 1941 (Barbarossa)."},
  {"deck":"histoire","id":"h2o","chapitre":"Les régimes totalitaires","q":"Qu'est-ce que l'antifascisme et les Fronts populaires des années 1930 ?","a":"Réaction à la montée des fascismes. En France, le Front populaire (socialistes + radicaux + communistes) remporte les élections de mai 1936. Gouvernement Blum : congés payés, semaine de 40h, conventions collectives. Victoire symbolique de la gauche unie face au danger fasciste."},

  {"deck":"histoire","id":"h3i","chapitre":"La Seconde Guerre mondiale","q":"Qu'est-ce que l'opération Barbarossa (22 juin 1941) ?","a":"Invasion de l'URSS par l'Allemagne nazie (3 millions de soldats, plus grande opération militaire de l'Histoire). Objectif : conquête de l'espace vital à l'Est, élimination du communisme. Succès initiaux fulgurants puis enlisement devant Moscou (hiver 1941-42). Tournant de la guerre."},
  {"deck":"histoire","id":"h3j","chapitre":"La Seconde Guerre mondiale","q":"Qu'est-ce que la bataille de Stalingrad (1942-1943) ?","a":"Juillet 1942 – février 1943 : bataille la plus meurtrière de l'Histoire (~2 millions de morts). La 6e armée allemande (Paulus) est encerclée et capitule. 1ère grande défaite allemande. Tournant psychologique majeur : l'armée allemande n'est plus invincible. Début du recul allemand à l'Est."},
  {"deck":"histoire","id":"h3k","chapitre":"La Seconde Guerre mondiale","q":"Qu'est-ce que Pearl Harbor (7 décembre 1941) et ses conséquences ?","a":"Attaque surprise de la marine japonaise sur la base navale américaine de Pearl Harbor (Hawaï). 2 400 morts américains, plusieurs cuirassés coulés. Le lendemain, les USA déclarent la guerre au Japon. Hitler déclare la guerre aux USA (11 déc.). Les USA entrent dans la 2GM : tournant décisif."},
  {"deck":"histoire","id":"h3l","chapitre":"La Seconde Guerre mondiale","q":"Qu'est-ce que la collaboration économique dans les pays occupés ?","a":"Dans les pays occupés (France, Belgique…), des entreprises et travailleurs collaborent avec l'économie de guerre allemande. En France : 650 000 travailleurs du STO, industrie française travaille pour l'Allemagne. La collaboration économique nourrit l'effort de guerre nazi et prolonge le conflit."},
  {"deck":"histoire","id":"h3m","chapitre":"La Seconde Guerre mondiale","q":"Qu'est-ce que la résistance armée dans les pays occupés (maquis, partisans) ?","a":"Partisans soviétiques (derrière les lignes allemandes), maquis français (FFI), résistants yougoslaves (Tito), polonais. Guérilla, sabotages, renseignement pour les Alliés. Répression féroce (massacres de civils, Oradour-sur-Glane, juin 1944). Symbolise la lutte populaire contre l'occupation."},
  {"deck":"histoire","id":"h3n","chapitre":"La Seconde Guerre mondiale","q":"Qu'est-ce que la conférence de Yalta (février 1945) ?","a":"Réunion des 3 Grands (Roosevelt, Churchill, Staline) pour organiser l'après-guerre. Décisions : partage de l'Allemagne en zones d'occupation, création de l'ONU, organisation des élections libres en Europe de l'Est (promesse non tenue par Staline). Pose les bases de l'ordre bipolaire de la Guerre froide."},
  {"deck":"histoire","id":"h3o","chapitre":"La Seconde Guerre mondiale","q":"Qu'est-ce que la guerre du Pacifique (1941-1945) ?","a":"Japon vs USA et Alliés. Expansion japonaise rapide (Philippines, Malaisie, Birmanie). Batailles navales décisives (Midway, juin 1942 : défaite japonaise). Stratégie américaine de saut de puce. Batailles d'Iwo Jima, Okinawa (pertes énormes). Bombes atomiques sur Hiroshima et Nagasaki → capitulation japonaise."},

  {"deck":"histoire","id":"h4i","chapitre":"La France dans la guerre","q":"Qu'est-ce que la zone libre et le gouvernement de Vichy ?","a":"Après l'armistice (juin 1940), la France est divisée : zone occupée (Nord, côte atlantique) et zone libre (Sud, capital : Vichy). Le régime de Vichy dirige la zone libre. En nov. 1942, après le débarquement allié en Afrique du Nord, les Allemands envahissent la zone libre."},
  {"deck":"histoire","id":"h4j","chapitre":"La France dans la guerre","q":"Qu'est-ce que la rafle du Vél d'Hiv (16-17 juillet 1942) ?","a":"Opération organisée par la police française : 13 152 Juifs (dont 4 000 enfants) arrêtés à Paris et parqués dans le Vélodrome d'Hiver. Conditions inhumaines. Déportés vers Auschwitz via Drancy. Symbole de la collaboration de la France dans la Shoah. Chirac reconnaît la responsabilité de l'État français en 1995."},
  {"deck":"histoire","id":"h4k","chapitre":"La France dans la guerre","q":"Qui est Jean Moulin et quel est son rôle dans la Résistance ?","a":"Préfet résistant envoyé par De Gaulle en France occupée (jan. 1942). Il unifie les mouvements de résistance dans le Conseil National de la Résistance (CNR, mai 1943). Arrêté par Klaus Barbie en juin 1943, torturé, il meurt sans parler. Panthéonisé en 1964 (discours d'André Malraux)."},
  {"deck":"histoire","id":"h4l","chapitre":"La France dans la guerre","q":"Qu'est-ce que la France Libre de De Gaulle ?","a":"Mouvement fondé après l'Appel du 18 juin 1940. Siège à Londres. Forces françaises libres (FFL) combattent aux côtés des Alliés. CFLN (Comité français de libération nationale, 1943, Alger). Progressivement reconnu comme gouvernement légitime par les Alliés. De Gaulle entre triomphalement à Paris le 25 août 1944."},
  {"deck":"histoire","id":"h4m","chapitre":"La France dans la guerre","q":"Comment les Juifs de France ont-ils été persécutés sous Vichy ?","a":"Statut des Juifs (oct. 1940) : exclusion des fonctions publiques, professions libérales, médias. Port de l'étoile jaune en zone occupée (juin 1942). Rafles et déportations vers les camps d'extermination. ~75 000 Juifs déportés de France, dont 2 500 reviendront. Vichy agit souvent sans pression directe des nazis."},
  {"deck":"histoire","id":"h4n","chapitre":"La France dans la guerre","q":"Qu'est-ce que l'épuration après la Libération (1944-1945) ?","a":"Épuration sauvage : exécutions sommaires de collaborateurs (~9 000 morts), tontes des femmes ayant eu des relations avec des Allemands. Épuration légale : procès (Pétain condamné à mort, peine commuée), ~6 700 condamnés à mort (dont ~800 exécutés). Beaucoup de collaborateurs échappent à la justice."},
  {"deck":"histoire","id":"h4o","chapitre":"La France dans la guerre","q":"Qu'est-ce que la déportation et les camps de concentration nazis ?","a":"Système concentrationnaire nazi : camps de travail forcé (Dachau, Buchenwald) et camps d'extermination (Auschwitz-Birkenau, Treblinka). Les déportés (Juifs, Résistants, Roms, homosexuels…) subissent travail forcé, famine, expériences médicales. ~6 millions de Juifs assassinés dans la Shoah."},

  {"deck":"histoire","id":"h5i","chapitre":"La France de la IVe à la Ve République","q":"Qu'est-ce que la guerre d'Indochine (1946-1954) ?","a":"Guerre de décolonisation contre le Viêt Minh (Ho Chi Minh) communiste. Défaite française à Diên Biên Phu (mai 1954). Accords de Genève (juil. 1954) : indépendance du Viêtnam, Laos, Cambodge. Pierre Mendès France signe la paix. Traumatisme militaire précédant la guerre d'Algérie."},
  {"deck":"histoire","id":"h5j","chapitre":"La France de la IVe à la Ve République","q":"Qu'est-ce que les Trente Glorieuses (1945-1975) ?","a":"Période de forte croissance économique en France : ~5 % de croissance annuelle, plein emploi, hausse du niveau de vie, développement de la société de consommation (voiture, télé, électroménager). État providence : Sécurité sociale (1945), allocations familiales. Exode rural et urbanisation massive."},
  {"deck":"histoire","id":"h5k","chapitre":"La France de la IVe à la Ve République","q":"Qu'est-ce que le gaullisme et ses grands principes ?","a":"Courant politique fondé par De Gaulle : indépendance nationale (politique étrangère autonome, force de frappe nucléaire), grandeur de la France, État fort avec président puissant, refus des blocs (URSS et USA), réconciliation franco-allemande. Retrait de l'OTAN en 1966."},
  {"deck":"histoire","id":"h5l","chapitre":"La France de la IVe à la Ve République","q":"Quelles sont les grandes alternances politiques de la Ve République ?","a":"1981 : première alternance, Mitterrand (PS) élu président. 1986-88 : cohabitation Mitterrand/Chirac. 1995 : Chirac (RPR) élu. 2007 : Sarkozy (UMP). 2012 : Hollande (PS). 2017 : Macron (En Marche). La Ve République a permis des alternances dans la continuité institutionnelle."},
  {"deck":"histoire","id":"h5m","chapitre":"La France de la IVe à la Ve République","q":"Qu'est-ce que la politique de réconciliation franco-allemande ?","a":"Après la 2GM, De Gaulle et Adenauer signent le Traité de l'Élysée (1963) : coopération franco-allemande dans tous les domaines. L'Office Franco-Allemand de la Jeunesse favorise les échanges. Moteur de la construction européenne. Symbole : poignée de main Mitterrand-Kohl à Verdun (1984)."},
  {"deck":"histoire","id":"h5n","chapitre":"La France de la IVe à la Ve République","q":"Qu'est-ce que la politique sociale du Front populaire (1936) et ses héritages ?","a":"Gouvernement Blum (juin 1936) : accords Matignon → congés payés (2 semaines), semaine de 40h, augmentations de salaires, conventions collectives. 1ère fois que l'État arbitre les relations sociales. Héritage durable : modèle social français, rôle des syndicats, vacances pour tous."},
  {"deck":"histoire","id":"h5o","chapitre":"La France de la IVe à la Ve République","q":"Qu'est-ce que le référendum de 1969 et la démission de De Gaulle ?","a":"De Gaulle engage sa démission sur un référendum réformant le Sénat et créant des régions. Il est battu (53 % de non). Il démissionne immédiatement (28 avril 1969), fidèle à sa conception plébiscitaire du pouvoir. Meurt le 9 novembre 1970. Pompidou lui succède."},

  {"deck":"histoire","id":"h6i","chapitre":"Mondialisation et flux mondiaux","q":"Qu'est-ce que la conteneurisation et son rôle dans la mondialisation ?","a":"Le conteneur standardisé (Malcolm McLean, 1956) révolutionne le transport maritime : chargement/déchargement mécanisé, coûts divisés par 10, sécurité accrue. Les mégaports (Shanghai, Singapour, Rotterdam) traitent des millions de conteneurs. Rend les échanges mondiaux massivement moins chers."},
  {"deck":"histoire","id":"h6j","chapitre":"Mondialisation et flux mondiaux","q":"Qu'est-ce que les paradis fiscaux et leur rôle dans la mondialisation financière ?","a":"Territoires à fiscalité très basse ou nulle (îles Caïmans, Luxembourg, Delaware…). Attireent capitaux des FTN et fortunes privées. Favorisent l'optimisation fiscale (légale) et l'évasion fiscale (illégale). Représentent ~20-30 % des flux financiers mondiaux. Cibles de la régulation internationale (OCDE, G20)."},
  {"deck":"histoire","id":"h6k","chapitre":"Mondialisation et flux mondiaux","q":"Qu'est-ce que les pays émergents (BRICS) et leur rôle dans la mondialisation ?","a":"Brésil, Russie, Inde, Chine, Afrique du Sud : économies en forte croissance. La Chine est devenue le 1er exportateur mondial (2009) et la 2e puissance économique. Ces pays remettent en cause la domination occidentale. La Chine investit massivement en Afrique et en Asie centrale (routes de la soie)."},
  {"deck":"histoire","id":"h6l","chapitre":"Mondialisation et flux mondiaux","q":"Quelles sont les critiques de la mondialisation ?","a":"• Creuse les inégalités (gagnants/perdants) \n• Délocalise des emplois industriels dans les pays riches\n• Détruit les cultures locales (McDonaldisation)\n• Accélère le réchauffement climatique\n• Favorise les multinationales au détriment des États\n• Crises financières contagieuses (2008)\nEn réaction : altermondialisme (Forum social de Porto Alegre)"},
  {"deck":"histoire","id":"h6m","chapitre":"Mondialisation et flux mondiaux","q":"Qu'est-ce que les migrations internationales et leur géographie ?","a":"~280 millions de migrants internationaux. Flux principaux : Sud→Nord (Afrique→Europe, Amérique latine→USA) et Sud→Sud. Causes : économiques (travail), climatiques, politiques (réfugiés). Remises de fonds vers les pays d'origine : ~700 Mds$/an (> aide au développement). Tensions politiques en Europe."},
  {"deck":"histoire","id":"h6n","chapitre":"Mondialisation et flux mondiaux","q":"Qu'est-ce que l'économie-monde et la hiérarchie des espaces mondiaux ?","a":"Centre dominant : la Triade (USA, UE, Japon/Chine). Semi-périphérie : pays émergents (Inde, Brésil, Mexique…). Périphérie intégrée : fournisseurs de matières premières. Marges : PMA (Afrique subsaharienne) peu intégrées. Cette hiérarchie n'est pas figée : la Chine a progressé spectaculairement."},
  {"deck":"histoire","id":"h6o","chapitre":"Mondialisation et flux mondiaux","q":"Qu'est-ce que l'internet et la révolution numérique dans la mondialisation ?","a":"Internet (1990s) accélère les flux d'information en temps réel. Commerce électronique (Amazon, Alibaba). Plateformes numériques mondiales (Google, Meta). Travail à distance (nomadisme numérique). Fake news et bulles de filtre. Fracture numérique : 1/3 de l'humanité encore non connecté. Les GAFAM concentrent le pouvoir numérique."},

  {"deck":"histoire","id":"h7i","chapitre":"L'Union européenne","q":"Qu'est-ce que le Parlement européen et comment fonctionne-t-il ?","a":"Seule institution de l'UE élue au suffrage universel direct (depuis 1979, tous les 5 ans). 705 eurodéputés. Co-législateur avec le Conseil de l'UE. Vote le budget de l'UE. Peut censurer la Commission. Siège à Strasbourg (sessions plénières) et Bruxelles (commissions). Groupes politiques, pas partis nationaux."},
  {"deck":"histoire","id":"h7j","chapitre":"L'Union européenne","q":"Qu'est-ce que le marché unique européen ?","a":"Espace sans frontières intérieures assurant la libre circulation des 4 libertés : marchandises, services, capitaux et personnes. Créé progressivement depuis le Traité de Rome (1957), achevé en 1993. Harmonisation des normes. 450 millions de consommateurs. Le plus grand marché intégré du monde."},
  {"deck":"histoire","id":"h7k","chapitre":"L'Union européenne","q":"Quels sont les principaux élargissements de l'UE ?","a":"1957 : 6 fondateurs (France, Allemagne, Italie, Belgique, Pays-Bas, Luxembourg). 1973 : RU, Irlande, Danemark. 1986 : Espagne, Portugal. 1995 : Autriche, Finlande, Suède. 2004 : 10 pays d'Europe de l'Est et centrale. 2007 : Bulgarie, Roumanie. 2013 : Croatie. Brexit (2020) : RU quitte l'UE."},
  {"deck":"histoire","id":"h7l","chapitre":"L'Union européenne","q":"Qu'est-ce que la crise de la zone euro (2010-2015) ?","a":"La Grèce révèle une dette publique cachée → les marchés s'affolent. Contagion à l'Irlande, Portugal, Espagne, Italie. Plans de sauvetage (FMI + BCE + UE) assortis d'austérité sévère. La BCE (Draghi : « whatever it takes », 2012) stabilise la situation. Révèle les failles de l'union monétaire sans union budgétaire."},
  {"deck":"histoire","id":"h7m","chapitre":"L'Union européenne","q":"Qu'est-ce que la politique de cohésion (fonds structurels) de l'UE ?","a":"Politique visant à réduire les inégalités entre régions. Fonds FEDER (développement régional), FSE (emploi), Fonds de cohésion (pays les moins riches). ~1/3 du budget UE. A contribué au rattrapage économique de l'Espagne, Portugal, Irlande, puis des pays d'Europe de l'Est."},
  {"deck":"histoire","id":"h7n","chapitre":"L'Union européenne","q":"Quels sont les symboles et valeurs de l'Union européenne ?","a":"Symboles : drapeau bleu aux 12 étoiles d'or, hymne (Ode à la joie de Beethoven), devise « Unie dans la diversité », journée de l'Europe (9 mai). Valeurs (art. 2 TUE) : dignité humaine, liberté, démocratie, égalité, État de droit, droits de l'homme. Monnaie : l'euro pour 20 États membres."},
  {"deck":"histoire","id":"h7o","chapitre":"L'Union européenne","q":"Qu'est-ce que la politique de défense et de sécurité commune (PESC/PSDC) de l'UE ?","a":"L'UE cherche à développer une capacité de défense autonome. Politique étrangère et de sécurité commune (PESC, 1992). Politique de sécurité et de défense commune (PSDC). Missions civiles et militaires (Mali, Bosnie). Limite : chaque État garde sa souveraineté militaire. La guerre en Ukraine relance le débat sur l'armée européenne."},

  # ═══════════════════════════════════════════════════════════════════════
  # FRANÇAIS
  # ═══════════════════════════════════════════════════════════════════════
  {"deck":"francais","id":"fr1i","chapitre":"Humanisme et Lumières","q":"Qu'est-ce que le scepticisme de Montaigne dans les Essais ?","a":"Montaigne doute de tout, y compris de lui-même (« Que sais-je ? »). Il pratique l'introspection (s'observe lui-même comme objet d'étude). Refuse les certitudes et les dogmes. Prône la tolérance et la relativité des jugements. Les Essais (1580-1588) inaugurent le genre de l'essai littéraire."},
  {"deck":"francais","id":"fr1j","chapitre":"Humanisme et Lumières","q":"Qu'est-ce que le Traité sur la tolérance de Voltaire (1763) ?","a":"Écrit après l'affaire Calas (protestant exécuté à tort pour meurtre). Voltaire défend la tolérance religieuse et critique le fanatisme. Argue que toutes les religions doivent coexister pacifiquement. L'une des premières œuvres modernes défendant les droits de l'homme et la liberté de conscience."},
  {"deck":"francais","id":"fr1k","chapitre":"Humanisme et Lumières","q":"Qu'est-ce que Candide de Voltaire et sa thèse ?","a":"Conte philosophique (1759) : Candide, élevé dans l'optimisme de Pangloss (« tout est pour le mieux dans le meilleur des mondes possibles »), traverse catastrophes, guerres, tremblements de terre. Conclusion : « Il faut cultiver notre jardin » = rejeter l'optimisme naïf et agir concrètement sur le monde."},
  {"deck":"francais","id":"fr1l","chapitre":"Humanisme et Lumières","q":"Qu'est-ce que Gargantua de Rabelais et l'idéal humaniste ?","a":"Roman (1534) : géant Gargantua éduqué selon la méthode scolastique absurde, puis rééduqué à la mode humaniste (curiosité universelle, langues, sciences, exercice physique). Abbaye de Thélème : « Fais ce que voudras » = liberté naturelle et confiance en l'homme. Humour, satire, foi en le progrès."},
  {"deck":"francais","id":"fr1m","chapitre":"Humanisme et Lumières","q":"Qu'est-ce que le De l'esprit des lois de Montesquieu (1748) ?","a":"Analyse comparée des systèmes politiques. Théorie de la séparation des 3 pouvoirs : législatif (lois), exécutif (application), judiciaire (jugement) — chacun devant contrôler les autres (checks and balances). Inspiration des constitutions américaine (1787) et française (1791). Critique de la monarchie absolue."},
  {"deck":"francais","id":"fr1n","chapitre":"Humanisme et Lumières","q":"Quelle est la structure d'une argumentation en français ?","a":"Thèse (position défendue) + arguments (raisons logiques) + exemples (illustrations concrètes) + contre-arguments (objections réfutées) + conclusion (synthèse + ouverture). Pour un plan dialectique : thèse / antithèse / synthèse. L'efficacité repose sur la logique, les preuves et la rhétorique."},
  {"deck":"francais","id":"fr1o","chapitre":"Humanisme et Lumières","q":"Qu'est-ce que la lettre persane de Montesquieu (1721) ?","a":"Roman épistolaire : deux Persans (Rica et Usbek) visitent la France et écrivent leurs impressions à leurs amis. Regard extérieur naïf permet de critiquer les institutions françaises (monarchie, Église, coutumes). Technique du regard étranger = distanciation satirique. Premier grand succès des Lumières."},

  {"deck":"francais","id":"fr2i","chapitre":"Le Roman","q":"Qu'est-ce que le roman psychologique ?","a":"Centre l'intérêt sur la vie intérieure des personnages : émotions, motivations, conflits intérieurs. Monologue intérieur, discours indirect libre. Auteurs : Madame de La Fayette (La Princesse de Clèves), Stendhal, Proust (À la recherche du temps perdu — flux de conscience). S'oppose au roman d'action."},
  {"deck":"francais","id":"fr2j","chapitre":"Le Roman","q":"Comment analyser une description dans un roman (portrait, lieu) ?","a":"1) Type : portrait physique/moral, paysage, intérieur. 2) Point de vue : qui décrit ? (omniscient / focalisation interne). 3) Organisation : du général au particulier, haut/bas, intérieur/extérieur. 4) Registre : réaliste, lyrique, fantastique ? 5) Valeur symbolique : que révèle la description sur le personnage/thème ?"},
  {"deck":"francais","id":"fr2k","chapitre":"Le Roman","q":"Qu'est-ce que le discours indirect libre ?","a":"Technique narrative fondant paroles/pensées du personnage dans la narration sans guillemets ni verbe introducteur. Ex : « Elle était fatiguée. La vie ne valait rien. » (pensées de l'héroïne sans « elle pensait que… »). Flaubert en fait un usage systématique. Crée complicité et ambiguïté narrateur/personnage."},
  {"deck":"francais","id":"fr2l","chapitre":"Le Roman","q":"Qu'est-ce que Madame Bovary de Flaubert et le bovarysme ?","a":"Roman (1857) : Emma Bovary, femme de médecin de province, rêve d'une vie romantique et exaltante. Déçue par la réalité terne, elle s'illusionne, s'endette, prend des amants. Le « bovarysme » désigne le fait de se voir autrement qu'on n'est, de fuir le réel dans l'imaginaire. Procès pour immoralité."},
  {"deck":"francais","id":"fr2m","chapitre":"Le Roman","q":"Qu'est-ce que le roman du XXe s. (existentialiste, absurde) ?","a":"Sartre (La Nausée, 1938) : l'existence précède l'essence, l'homme crée son propre sens. Camus (L'Étranger, 1942) : Meursault, le « héros absurde » indifférent aux conventions sociales. L'absurde = contradiction entre désir de sens de l'homme et silence du monde. Roman engagé, existentialiste, philosophique."},
  {"deck":"francais","id":"fr2n","chapitre":"Le Roman","q":"Qu'est-ce qu'un roman dystopique ? Exemples.","a":"Roman décrivant une société future totalitaire et cauchemardesque (anti-utopie). Critique des dérives de la modernité (surveillance, manipulation, conformisme). Ex : 1984 (Orwell, 1949 — Big Brother), Le Meilleur des mondes (Huxley, 1932 — bonheur chimique imposé), La Servante écarlate (Atwood, 1985)."},
  {"deck":"francais","id":"fr2o","chapitre":"Le Roman","q":"Comment analyser un excipit (fin) de roman ?","a":"L'excipit doit : 1) Clore l'intrigue (résolution ou ouverture intentionnelle). 2) Donner un sens final à l'œuvre. 3) Créer un effet final mémorable. Types : fin fermée (tout résolu), fin ouverte (ambiguïté), épilogue (avenir des personnages). Analyser : ton, registre, dernier mot/image symbolique."},

  {"deck":"francais","id":"fr3e","chapitre":"Le Théâtre","q":"Comment analyser une scène d'exposition au théâtre ?","a":"La scène d'exposition doit : 1) Présenter les personnages principaux et leurs relations. 2) Situer l'action (époque, lieu). 3) Exposer la situation initiale et l'enjeu. 4) Accrocher le spectateur. Analyser : techniques d'exposition (dialogue, monologue, confiant), informations données, effet de curiosité créé."},
  {"deck":"francais","id":"fr3f","chapitre":"Le Théâtre","q":"Qu'est-ce qu'un monologue délibératif au théâtre ?","a":"Discours d'un personnage seul en scène qui réfléchit à voix haute à un dilemme moral (partir ou rester, agir ou non). Permet de montrer le conflit intérieur. Ex : monologue de Rodrigue dans Le Cid (Corneille) — honneur vs amour. Technique pour extérioriser la psychologie sans narrateur."},
  {"deck":"francais","id":"fr3g","chapitre":"Le Théâtre","q":"Qu'est-ce que le théâtre de l'absurde (Ionesco, Beckett) ?","a":"Courant des années 1950-60 : représente l'absurdité de la condition humaine par des situations illogiques, dialogues sans communication, personnages sans évolution. Ex : En attendant Godot (Beckett) : deux vagabonds attendent indéfiniment quelqu'un qui ne vient pas. La Cantatrice chauve (Ionesco) : dialogues automatiques et vides de sens."},
  {"deck":"francais","id":"fr3h","chapitre":"Le Théâtre","q":"Qu'est-ce que Phèdre de Racine et la notion de fatalité tragique ?","a":"Phèdre aime son beau-fils Hippolyte — amour interdit, impossible. Elle ne peut ni avouer ni taire. Tous ses efforts pour échapper à sa passion précipitent la catastrophe. La fatalité tragique = le héros est pris dans un engrenage inévitable malgré ses efforts. Culpabilité, honte, mort finale."},
  {"deck":"francais","id":"fr3i","chapitre":"Le Théâtre","q":"Qu'est-ce que le vaudeville et la comédie de boulevard ?","a":"Vaudeville (XIXe s.) : comédie légère basée sur quiproquos, portes qui claquent, maris trompés, adultères. Rythme rapide, rebondissements. Ex : Feydeau (La Dame de chez Maxim). Comédie de boulevard : divertissement bourgeois du XXe s. But : faire rire sans profondeur. Contraire du théâtre engagé."},
  {"deck":"francais","id":"fr3j","chapitre":"Le Théâtre","q":"Qu'est-ce que Dom Juan de Molière et ses thèmes ?","a":"Don Juan, libertin impie et séducteur, refuse toute autorité (divine, sociale, paternelle). Il accumule les conquêtes et les mensonges. La statue du Commandeur l'emporte en enfer. Thèmes : libertinage, hypocrisie sociale, rapport à la mort. Sganarelle représente la morale populaire face à l'aristocratie dissolue."},
  {"deck":"francais","id":"fr3k","chapitre":"Le Théâtre","q":"Comment rédiger un commentaire de texte de théâtre ?","a":"1) Axe 1 : la scène comme moment de tension dramatique (enjeux, conflit). 2) Axe 2 : la caractérisation des personnages (tirades, répliques, didascalies). 3) Axe 3 : le registre (tragique, comique) et les procédés. Attention aux didascalies (indications scéniques) qui révèlent la mise en scène."},

  {"deck":"francais","id":"fr4i","chapitre":"La Poésie","q":"Qu'est-ce qu'un sonnet et quelle en est la structure ?","a":"Poème fixe de 14 vers : 2 quatrains (ABBA ABBA) + 2 tercets (CCD EDE ou variation). Forme venue d'Italie (Pétrarque), popularisée en France par Du Bellay et Ronsard. Souvent le volta (charnière) entre les quatrains (description) et les tercets (réflexion/conclusion). Ex : Heureux qui, comme Ulysse (Du Bellay)."},
  {"deck":"francais","id":"fr4j","chapitre":"La Poésie","q":"Qu'est-ce que le symbolisme (Baudelaire, Verlaine, Rimbaud) ?","a":"Courant poétique (fin XIXe s.) : le poème suggère par les symboles, les sons, les images plutôt qu'il ne décrit. Synesthésies (correspondances entre sens). Verlaine : musicalité (« De la musique avant toute chose »). Rimbaud : dérèglement des sens, voyance. Baudelaire : spleen et idéal, fleurs du mal."},
  {"deck":"francais","id":"fr4k","chapitre":"La Poésie","q":"Qu'est-ce que le romantisme en poésie (Lamartine, Hugo, Musset) ?","a":"Expression du moi lyrique, des sentiments intenses, de la mélancolie. La nature comme miroir de l'âme (« paysage état d'âme »). Thèmes : amour, mort, solitude, liberté. Lamartine (Le Lac), Hugo (Les Contemplations), Musset (La Nuit de mai). Rupture avec la régularité classique."},
  {"deck":"francais","id":"fr4l","chapitre":"La Poésie","q":"Qu'est-ce que le surréalisme en poésie (Breton, Éluard, Aragon) ?","a":"Mouvement (1920s-30s) explorant l'inconscient et le rêve. Écriture automatique : laisser venir les mots sans censure. Images insolites et associations libres. Breton (Manifeste du surréalisme, 1924). Éluard (Liberté). Aragon. Lien avec la psychanalyse de Freud et les traumatismes de la 1GM."},
  {"deck":"francais","id":"fr4m","chapitre":"La Poésie","q":"Qu'est-ce que l'ode et l'élégie comme formes poétiques ?","a":"Ode : poème lyrique d'éloge, souvent célébrant un être, un événement, une idée. Ton solennel. Pindarique (strophes régulières) ou anacrétique (légère). Ronsard en écrit en français. Élégie : poème de deuil, de plainte amoureuse ou funèbre. Ton mélancolique. Lamartine (Le Lac) est souvent considéré comme une élégie."},
  {"deck":"francais","id":"fr4n","chapitre":"La Poésie","q":"Comment analyser un poème méthodiquement ?","a":"1) Forme : nombre de vers, strophes, schéma rimique, mètre. 2) Fond : thème, registre (lyrique, épique, satirique…). 3) Procédés : figures de style, images, sonorités. 4) Mouvement littéraire. 5) Lecture linéaire (vers par vers) ou plan thématique. Conclusion : portée du poème, effet sur le lecteur."},
  {"deck":"francais","id":"fr4o","chapitre":"La Poésie","q":"Quels sont les grands thèmes de la poésie de Rimbaud ?","a":"Révolte contre la société bourgeoise, fuite (« Je est un autre »), exploration de l'inconscient (Le Bateau ivre, Les Illuminations). Théorie du voyant : le poète se fait voyant par un « dérèglement de tous les sens ». Adolescent génial qui abandonne la poésie à 20 ans. Une Saison en enfer (1873)."},

  {"deck":"francais","id":"fr5i","chapitre":"Figures de style","q":"Qu'est-ce que l'ironie et comment la reconnaître ?","a":"Dire le contraire de ce qu'on pense pour critiquer. Reconnaissable par : contexte (éloge exagéré d'une chose négative), ton décalé, sous-entendu. Ex : Voltaire louant la guerre dans Candide. L'ironie socratique feint l'ignorance pour amener l'interlocuteur à se contredire. Outil critique majeur des Lumières."},
  {"deck":"francais","id":"fr5j","chapitre":"Figures de style","q":"Qu'est-ce que l'euphémisme et la litote ?","a":"Euphémisme : atténuer une réalité dure pour la rendre plus acceptable. Ex : « il nous a quittés » pour « il est mort ». Litote : dire moins pour suggérer plus. Ex : « Je ne te déteste pas » = « Je t'aime » (Corneille, Le Cid). La litote crée un effet d'understatement poignant dans la tragédie."},
  {"deck":"francais","id":"fr5k","chapitre":"Figures de style","q":"Qu'est-ce qu'une métaphore filée ?","a":"Métaphore développée sur plusieurs vers ou paragraphes. Ex : si on compare la vie à un voyage, une métaphore filée utilisera route, carrefour, bagages, destination, passeport tout au long du texte. Crée une cohérence imaginaire et approfondit la comparaison. Fréquente dans la poésie romantique et baroque."},
  {"deck":"francais","id":"fr5l","chapitre":"Figures de style","q":"Qu'est-ce que l'anaphore et quel est son effet ?","a":"Répétition d'un mot ou groupe de mots en début de plusieurs vers ou phrases. Ex : « J'ai vu, j'ai vu… », « Liberté, liberté… ». Effets : insistance, crescendo rhétorique, martèlement d'une idée, élan oratoire. Très utilisée dans les discours politiques (Churchill, De Gaulle) et la poésie engagée."},
  {"deck":"francais","id":"fr5m","chapitre":"Figures de style","q":"Qu'est-ce que la synesthésie et qui l'utilise ?","a":"Mélange de sensations différentes dans une même image. Ex : « parfum vert » (associe odorat + vision), « sons dorés » (ouïe + vue). Baudelaire dans Correspondances : « Les parfums, les couleurs et les sons se répondent ». Technique symboliste exprimant les correspondances secrètes entre les sens."},
  {"deck":"francais","id":"fr5n","chapitre":"Figures de style","q":"Qu'est-ce que l'oxymore et le paradoxe ?","a":"Oxymore : alliance de deux mots contradictoires dans une expression. Ex : « soleil noir » (Nerval), « douce violence », « obscure clarté » (Corneille). Paradoxe : idée qui semble contradictoire mais révèle une vérité profonde. Ex : « Plus on connaît, plus on sait qu'on ne sait rien » (Socrate)."},
  {"deck":"francais","id":"fr5o","chapitre":"Figures de style","q":"Qu'est-ce que la prosopopée et l'apostrophe ?","a":"Prosopopée : faire parler un absent, un mort, une abstraction ou un objet inanimé. Ex : la Nature parle à l'homme. Apostrophe : interpellation directe d'un être absent, d'une abstraction, du lecteur. Ex : « Ô mort, vieux capitaine, il est temps ! » (Baudelaire). Effets : solennité, pathétique, vivification."},

  {"deck":"francais","id":"fr6i","chapitre":"Versification","q":"Qu'est-ce qu'un alexandrin et un décasyllabe ?","a":"Alexandrin : vers de 12 syllabes, coupé par une césure au 6e. Le vers noble du théâtre et de la poésie classiques. Ex : « Ra-cine / est le plus / grand des / poètes / fran-çais ». Décasyllabe : vers de 10 syllabes, césure après la 4e ou 6e. Utilisé dans les chansons de geste (épopées médiévales) et par Ronsard."},
  {"deck":"francais","id":"fr6j","chapitre":"Versification","q":"Qu'est-ce qu'un enjambement, un rejet et un contre-rejet ?","a":"Enjambement : le sens déborde d'un vers sur le suivant sans pause syntaxique. Rejet : mot ou groupe court rejeté au début du vers suivant (effet de surprise, d'insistance). Contre-rejet : mot ou groupe en fin de vers qui appelle la suite. Rompent le rythme attendu pour créer un effet expressif."},
  {"deck":"francais","id":"fr6k","chapitre":"Versification","q":"Comment compter les syllabes en poésie française (règles de décompte) ?","a":"1) Le « e » muet en fin de mot compte si suivi d'une consonne (sauf en fin de vers). 2) La synérèse : deux voyelles prononcées en une syllabe (vi-on-lon = 3 syl.). 3) La diérèse : deux voyelles prononcées séparément (vi-o-lon = 4 syl.). 4) L'élision : « e » muet s'efface devant une voyelle."},
  {"deck":"francais","id":"fr6l","chapitre":"Versification","q":"Quels sont les différents types de strophes ?","a":"Distique : 2 vers. Tercet : 3 vers. Quatrain : 4 vers (le plus courant). Quintil : 5 vers. Sizain : 6 vers. Huitain : 8 vers. Sonnet : 2 quatrains + 2 tercets. L'organisation en strophes rythme le poème et crée des unités de sens. Le poème en prose (Baudelaire) supprime la contrainte strophique."},
  {"deck":"francais","id":"fr6m","chapitre":"Versification","q":"Qu'est-ce que les rimes plates, croisées et embrassées ?","a":"Rimes plates (suivies) : AABB (deux par deux). Rimes croisées : ABAB (alternées). Rimes embrassées : ABBA (une enveloppe l'autre). Qualité des rimes : pauvres (1 son commun), suffisantes (2 sons), riches (3+ sons). Règle classique : alternance rimes féminines (terminant par « e » muet) et masculines."},
  {"deck":"francais","id":"fr6n","chapitre":"Versification","q":"Qu'est-ce que le vers libre (poésie moderne) ?","a":"Vers sans contraintes fixes de syllabe, rime ou strophe. Rythme créé par d'autres moyens : répétitions, coupes, anaphores, longueur variable des vers. Inauguré par Verlaine, Rimbaud (Illuminations), développé par Apollinaire (Alcools) qui supprime la ponctuation. Domine la poésie du XXe s."},
  {"deck":"francais","id":"fr6o","chapitre":"Versification","q":"Qu'est-ce qu'une allitération et une assonance ?","a":"Allitération : répétition de consonnes identiques dans des mots proches. Ex : « Pour qui sont ces serpents qui sifflent sur vos têtes » (Racine) — son [s] imitant le sifflement. Assonance : répétition de voyelles identiques. Ex : « Les sanglots longs des violons de l'automne » (Verlaine) — son [ɔ̃]. Créent musicalité et expressivité."},

  {"deck":"francais","id":"fr7i","chapitre":"Mouvements littéraires","q":"Qu'est-ce que le baroque (XVIe-XVIIe s.) et ses caractéristiques ?","a":"Mouvement fondé sur le mouvement, l'excès, les contrastes, l'illusion. Thèmes : vanité (tout passe), métamorphose, théâtre du monde. En littérature : style orné, images complexes (métaphores filées), instabilité. Ex : d'Aubigné (Les Tragiques), Agrippa d'Aubigné. S'oppose au classicisme par son exubérance."},
  {"deck":"francais","id":"fr7j","chapitre":"Mouvements littéraires","q":"Qu'est-ce que le classicisme (XVIIe s.) et ses valeurs ?","a":"Mouvement fondé sur la raison, l'ordre, l'équilibre, l'imitation des Anciens. Idéal : le beau idéal, l'universel, le juste milieu. Style : clarté, sobriété, « plaire et instruire » (Boileau, Art poétique). Auteurs : Molière, Racine, La Fontaine, La Bruyère. Règles strictes (unités au théâtre)."},
  {"deck":"francais","id":"fr7k","chapitre":"Mouvements littéraires","q":"Qu'est-ce que le romantisme (XIXe s.) et ses thèmes principaux ?","a":"Réaction contre le classicisme et la raison des Lumières. Valorise les sentiments, l'individu, la nature, le rêve, l'histoire. Le « mal du siècle » (mélancolie de la génération post-napoléonienne). Auteurs : Hugo, Lamartine, Vigny, Musset (France) ; Goethe, Byron (Europe). Liberté formelle."},
  {"deck":"francais","id":"fr7l","chapitre":"Mouvements littéraires","q":"Qu'est-ce que le Parnasse (XIXe s.) et l'Art pour l'Art ?","a":"Réaction contre le lyrisme romantique. Recherche de la perfection formelle, du travail ciselé (« l'Art pour l'Art »). Poèmes froids, sculptés, à sujets antiques ou exotiques. Leconte de Lisle, Théophile Gautier, Hérédia. Influence sur Baudelaire et les symbolistes. Priorité à la beauté sur l'engagement."},
  {"deck":"francais","id":"fr7m","chapitre":"Mouvements littéraires","q":"Qu'est-ce que l'existentialisme en littérature (Sartre, Camus) ?","a":"Courant philosophique et littéraire (1940s-50s) : l'existence précède l'essence (l'homme se définit par ses actes, pas par une nature prédéfinie). Liberté et responsabilité radicales. Engagement (littérature engagée). Sartre (La Nausée, Huis clos), Camus (L'Étranger, La Peste, Le Mythe de Sisyphe)."},
  {"deck":"francais","id":"fr7n","chapitre":"Mouvements littéraires","q":"Qu'est-ce que la négritude (Senghor, Césaire) ?","a":"Mouvement littéraire et politique (1930s-40s) de valorisation de la culture africaine et des valeurs noires face au colonialisme. Aimé Césaire (Cahier d'un retour au pays natal), Léopold Sédar Senghor. Réappropriation du terme « nègre ». Influence sur les mouvements de décolonisation et la littérature francophone."},
  {"deck":"francais","id":"fr7o","chapitre":"Mouvements littéraires","q":"Qu'est-ce que le naturalisme de Zola et ses principes ?","a":"Extension du réalisme : l'homme est un animal déterminé par l'hérédité et le milieu (influence du darwinisme et de la physiologie de Claude Bernard). Le romancier = savant qui expérimente (Roman expérimental, 1880). Documentation rigoureuse des milieux populaires. Cycle des Rougon-Macquart (20 romans, 1871-1893)."},

  {"deck":"francais","id":"fr8i","chapitre":"Méthodes","q":"Comment réussir une lecture linéaire (explication de texte) au bac ?","a":"1) Introduction : auteur, œuvre, extrait, thèse, plan. 2) Lecture linéaire : analyser le texte passage par passage dans l'ordre, en combinant fond et forme. 3) Conclusion : bilan + ouverture. Éviter le paraphrase (résumer sans analyser). Toujours citer le texte. Montrer comment les procédés servent le sens."},
  {"deck":"francais","id":"fr8j","chapitre":"Méthodes","q":"Comment réussir la dissertation au bac de français ?","a":"Plan dialectique ou thématique. 1) Introduction : accroche + problématique + annonce du plan. 2) Développement : 2-3 parties, chacune avec 2-3 sous-parties illustrées d'exemples littéraires. 3) Conclusion : réponse à la problématique + ouverture. Mobiliser des œuvres au programme et des œuvres personnelles."},
  {"deck":"francais","id":"fr8k","chapitre":"Méthodes","q":"Comment réussir la contraction de texte au bac ?","a":"Réduire un texte argumentatif à 1/4 de sa longueur en conservant toutes les idées essentielles. Méthode : 1) Repérer la thèse et les arguments. 2) Identifier les exemples à supprimer (conserver les idées, pas les illustrations). 3) Reformuler sans plagier. 4) Vérifier le compte de mots. Pas d'avis personnel."},
  {"deck":"francais","id":"fr8l","chapitre":"Méthodes","q":"Comment construire un plan de commentaire littéraire ?","a":"Chercher 2-3 axes qui répondent ensemble à la problématique. Chaque axe = une idée directrice, subdivisée en 2-3 sous-parties. Exemples : Axe 1 (registre) + Axe 2 (thème) + Axe 3 (portée). Éviter le plan descriptif/analytique/interprétatif trop mécanique. Partir toujours du texte, pas de connaissances générales."},
  {"deck":"francais","id":"fr8m","chapitre":"Méthodes","q":"Qu'est-ce qu'une problématique littéraire et comment en formuler une ?","a":"Question ouverte sur le sens ou l'intérêt d'un texte, qui dépasse le simple résumé. Formulations : « En quoi… ? », « Comment… ? », « Dans quelle mesure… ? ». Elle doit créer une tension (deux réponses possibles) que le devoir va résoudre. Éviter les problématiques fermées (oui/non) ou trop générales."},
  {"deck":"francais","id":"fr8n","chapitre":"Méthodes","q":"Comment réussir l'épreuve orale de français (grand oral) ?","a":"Présenter une question en lien avec 2 spécialités pendant 5 min, puis dialogue de 10 min avec le jury. Préparer : intro accrocheuse, plan clair, conclusion avec ouverture. Langage soigné, débit maîtrisé, contact visuel. Anticiper les questions du jury. Montrer sa capacité à nuancer et à penser par soi-même."},
  {"deck":"francais","id":"fr8o","chapitre":"Méthodes","q":"Quelles œuvres au programme étudier pour le bac de français (parcours) ?","a":"Les œuvres varient selon le parcours choisi. Exemples de groupements : Romans (Balzac, Zola, Camus), Poésie (Rimbaud, Apollinaire, Prévert), Théâtre (Molière, Beckett, Ionesco), Argumentation (Voltaire, Montaigne). Toujours avoir 5-6 œuvres maîtrisées pour illustrer la dissertation."},
]

# ═══════════════════════════════════════════════════════════════════════
# Injection
# ═══════════════════════════════════════════════════════════════════════
HTML_PATH = '/Users/stagiaire/flashcards/mobile.html'
OPEN_TAG  = '<script type="application/json" id="q-data">'
CLOSE_TAG = '</script>'

import json

with open(HTML_PATH, encoding='utf-8') as f:
    html = f.read()

s = html.find(OPEN_TAG)
assert s != -1, 'q-data block not found'
e = html.find(CLOSE_TAG, s + len(OPEN_TAG))

data = json.loads(html[s + len(OPEN_TAG):e])

for card in EXTRA:
    deck_id = card.pop('deck')
    deck = next((d for d in data['decks'] if d['id'] == deck_id), None)
    if deck is None:
        print(f'  ⚠ deck {deck_id} not found')
        continue
    existing_ids = {c['id'] for c in deck['cards']}
    if card['id'] not in existing_ids:
        deck['cards'].append(card)

new_json = json.dumps(data, ensure_ascii=False, indent=2)
html = html[:s + len(OPEN_TAG)] + '\n' + new_json + '\n' + html[e:]

with open(HTML_PATH, 'w', encoding='utf-8') as f:
    f.write(html)

print('✅ Done')
for d in data['decks']:
    print(f"  {d['emoji']} {d['name']}: {len(d['cards'])} cartes")
