#!/usr/bin/env python3
"""Ajoute 7 cartes supplémentaires par chapitre — Maths, SVT, Physique-Chimie."""
import json

EXTRA = [
  # ═══════════════════════════════════════════════════════════════════════
  # MATHS
  # ═══════════════════════════════════════════════════════════════════════
  {"deck":"maths","id":"m1i","chapitre":"Second degré","q":"Comment factoriser un trinôme ax²+bx+c quand Δ>0 ?","a":"ax²+bx+c = a(x−x₁)(x−x₂) où x₁ et x₂ sont les deux racines. Ex : 2x²−5x+3 → Δ=1, x₁=1, x₂=3/2 → 2(x−1)(x−3/2) = (x−1)(2x−3). Cette factorisation est utile pour résoudre des inéquations ou simplifier des fractions."},
  {"deck":"maths","id":"m1j","chapitre":"Second degré","q":"Comment résoudre une inéquation du second degré ax²+bx+c > 0 ?","a":"1) Trouver les racines x₁ et x₂ (avec x₁ < x₂). 2) Dresser le tableau de signe de ax²+bx+c. Si a>0 : positif à l'extérieur ]−∞;x₁[ ∪ ]x₂;+∞[, négatif à l'intérieur ]x₁;x₂[. Si a<0 : inverse. Si Δ<0 : même signe que a partout."},
  {"deck":"maths","id":"m1k","chapitre":"Second degré","q":"Qu'est-ce que la forme canonique d'un trinôme et à quoi sert-elle ?","a":"ax²+bx+c = a(x+b/2a)²−Δ/4a. Permet de lire directement le sommet S(−b/2a ; −Δ/4a) de la parabole et la valeur extrême. Utile pour l'étude de variations, optimisation (max/min). Ex : x²−4x+7 = (x−2)²+3 → minimum en x=2, valeur 3."},
  {"deck":"maths","id":"m1l","chapitre":"Second degré","q":"Comment résoudre une équation du type ax²+bx+c = 0 dans ℂ (Terminale) ?","a":"Si Δ<0, poser Δ=−|Δ|. Racines complexes conjuguées : z = (−b ± i√|Δ|) / 2a. Ex : x²−2x+5=0, Δ=4−20=−16. z = (2 ± 4i)/2 = 1±2i. En Terminale spécialité maths uniquement."},
  {"deck":"maths","id":"m1m","chapitre":"Second degré","q":"Qu'est-ce que la parabole et comment lire son graphe ?","a":"Représentation graphique de y=ax²+bx+c. Axe de symétrie : x=−b/2a. Sommet S(−b/2a ; f(−b/2a)). Si a>0 : parabole « souriante » (min). Si a<0 : « triste » (max). Intersections axe Ox : abscisses des racines. Intersection axe Oy : ordonnée à l'origine = c."},
  {"deck":"maths","id":"m1n","chapitre":"Second degré","q":"Comment résoudre un système avec une équation du second degré ?","a":"Ex : y=x²−1 et y=2x+2. Substituer : x²−1=2x+2 → x²−2x−3=0 → (x−3)(x+1)=0 → x=3 ou x=−1. Points d'intersection : (3;8) et (−1;0). Méthode : égaliser les deux expressions de y, résoudre l'équation du 2e degré obtenue."},
  {"deck":"maths","id":"m1o","chapitre":"Second degré","q":"Quand un problème d'optimisation conduit-il à un trinôme du second degré ?","a":"Problèmes de type : maximiser l'aire d'un rectangle sous contrainte de périmètre, minimiser un coût, trouver la trajectoire optimale. On modélise la grandeur à optimiser comme ax²+bx+c, puis on trouve le sommet de la parabole (valeur extrémale). L'axe de symétrie x=−b/2a donne la valeur optimale."},

  {"deck":"maths","id":"m2i","chapitre":"Suites numériques","q":"Comment démontrer qu'une suite est croissante ou décroissante ?","a":"Méthode 1 : calculer uₙ₊₁−uₙ. Si >0 : croissante ; si <0 : décroissante. Méthode 2 : si uₙ>0, étudier uₙ₊₁/uₙ. Si >1 : croissante ; si <1 : décroissante. Méthode 3 : si uₙ=f(n), étudier les variations de f sur [0;+∞[."},
  {"deck":"maths","id":"m2j","chapitre":"Suites numériques","q":"Qu'est-ce qu'une suite récurrente et comment calculer ses premiers termes ?","a":"Suite définie par uₙ₊₁=f(uₙ) et une valeur initiale u₀. Ex : u₀=1, uₙ₊₁=2uₙ+1 → u₁=3, u₂=7, u₃=15. Pour étudier : chercher si la suite est arithmétique/géométrique, ou utiliser le changement de variable vₙ=uₙ+k pour se ramener à une suite géométrique."},
  {"deck":"maths","id":"m2k","chapitre":"Suites numériques","q":"Comment démontrer qu'une suite converge par récurrence ?","a":"Méthode : 1) Montrer que la suite est monotone (croissante ou décroissante). 2) Montrer qu'elle est bornée (majorée si croissante, minorée si décroissante). Toute suite monotone bornée converge (théorème). La limite ℓ vérifie ℓ=f(ℓ) si uₙ₊₁=f(uₙ)."},
  {"deck":"maths","id":"m2l","chapitre":"Suites numériques","q":"Quelle est la somme des termes d'une suite arithmétique ?","a":"Sₙ = u₀+u₁+…+uₙ = (n+1)×(u₀+uₙ)/2 = (n+1)×(premier+dernier)/2. Aussi : Sₙ = (n+1)u₀ + n(n+1)/2 × r. Ex : 1+2+3+…+n = n(n+1)/2. Méthode : écrire la somme à l'endroit et à l'envers, additionner terme à terme."},
  {"deck":"maths","id":"m2m","chapitre":"Suites numériques","q":"Quelle est la somme des termes d'une suite géométrique ?","a":"Sₙ = u₀(1−qⁿ⁺¹)/(1−q) si q≠1. Si q=1 : Sₙ=(n+1)u₀. Formule à retenir : somme de n+1 termes = premier terme × (1−qⁿ⁺¹)/(1−q). Ex : 1+2+4+…+2ⁿ = 2ⁿ⁺¹−1. Utile pour les problèmes de placement bancaire, population en croissance."},
  {"deck":"maths","id":"m2n","chapitre":"Suites numériques","q":"Comment raisonner par récurrence (démonstration) ?","a":"1) Initialisation : vérifier la propriété au rang n₀ (souvent n=0 ou n=1). 2) Hérédité : supposer la propriété vraie au rang n (hypothèse de récurrence), démontrer qu'elle est vraie au rang n+1. 3) Conclusion : la propriété est vraie pour tout n≥n₀. Utiliser explicitement l'hypothèse de récurrence."},
  {"deck":"maths","id":"m2o","chapitre":"Suites numériques","q":"Comment modéliser un phénomène par une suite ?","a":"Ex : capital placé à taux r → suite géométrique (uₙ=u₀×(1+r)ⁿ). Population avec taux de croissance a et migration b → uₙ₊₁=a×uₙ+b (affine → suite arithmético-géométrique). Médicament : dose restante après chaque prise. Identifier : géométrique (×), arithmétique (+), ou affine (×+)."},

  {"deck":"maths","id":"m3i","chapitre":"Fonctions exponentielle et logarithme","q":"Quelles sont les propriétés algébriques de ln ?","a":"ln(ab) = ln(a)+ln(b). ln(a/b) = ln(a)−ln(b). ln(aⁿ) = n×ln(a). ln(1/a) = −ln(a). ln(√a) = ln(a)/2. Exemples : ln(6) = ln(2)+ln(3). ln(e²) = 2. Ces propriétés permettent de transformer des produits en sommes pour simplifier les calculs."},
  {"deck":"maths","id":"m3j","chapitre":"Fonctions exponentielle et logarithme","q":"Comment résoudre eˣ > k ou ln(x) < k ?","a":"eˣ > k (k>0) : x > ln(k). eˣ < k (k>0) : x < ln(k). ln(x) > k (x>0) : x > eᵏ. ln(x) < k (x>0) : 0 < x < eᵏ. Toujours vérifier le domaine de définition (ln défini uniquement pour x>0). Ces inéquations apparaissent souvent dans les études de fonctions."},
  {"deck":"maths","id":"m3k","chapitre":"Fonctions exponentielle et logarithme","q":"Quelles sont les limites fondamentales liées à l'exponentielle ?","a":"lim(x→+∞) eˣ = +∞. lim(x→−∞) eˣ = 0 (asymptote y=0). lim(x→+∞) eˣ/xⁿ = +∞ (exp domine tout polynôme). lim(x→−∞) xⁿeˣ = 0 (exp « écrase » les polynômes en −∞). Ces croissances comparées sont fondamentales pour les limites en +∞ et −∞."},
  {"deck":"maths","id":"m3l","chapitre":"Fonctions exponentielle et logarithme","q":"Comment étudier une fonction du type f(x) = eˣ·P(x) ?","a":"1) Domaine : ℝ. 2) Dériver : f'(x) = eˣ·P(x) + eˣ·P'(x) = eˣ(P(x)+P'(x)). Comme eˣ>0 toujours, le signe de f'(x) est celui de P(x)+P'(x). 3) Limites en ±∞ via croissances comparées. 4) Tableau de variations, extrema éventuels."},
  {"deck":"maths","id":"m3m","chapitre":"Fonctions exponentielle et logarithme","q":"Comment étudier une fonction du type f(x) = ln(g(x)) ?","a":"1) Domaine : g(x) > 0 (condition ln). 2) Dériver : f'(x) = g'(x)/g(x). 3) Signe de f' = signe de g'/g = signe de g' (car g>0 sur le domaine). 4) Limites : si g(x)→0⁺ alors f→−∞ ; si g(x)→+∞ alors f→+∞. Chercher asymptotes verticales où g s'annule."},
  {"deck":"maths","id":"m3n","chapitre":"Fonctions exponentielle et logarithme","q":"Qu'est-ce que la fonction exponentielle de base a (a>0, a≠1) ?","a":"aˣ = eˣ·ln(a). Propriétés : aˣ·aʸ = aˣ⁺ʸ, (aˣ)ʸ = aˣʸ. Si a>1 : croissante. Si 0<a<1 : décroissante. Dérivée : (aˣ)' = ln(a)·aˣ. Applications : croissance démographique (base e), placement financier (base 1+r), radioactivité (base e^(−λ))."},
  {"deck":"maths","id":"m3o","chapitre":"Fonctions exponentielle et logarithme","q":"Comment résoudre une équation du type aeˣ + be⁻ˣ = c ?","a":"Poser X = eˣ (donc X>0). L'équation devient aX + b/X = c → aX² − cX + b = 0. Résoudre ce trinôme en X, garder uniquement les solutions positives, puis x = ln(X). Ex : eˣ+e⁻ˣ = 3 → X+1/X=3 → X²−3X+1=0 → X=(3±√5)/2 (les deux sont >0)."},

  {"deck":"maths","id":"m4i","chapitre":"Dérivation","q":"Quelles sont les formules de dérivées des fonctions composées ?","a":"(f∘g)'(x) = g'(x)·f'(g(x)). Cas courants : (u²)' = 2u·u', (uⁿ)' = nu^(n-1)·u', (√u)' = u'/(2√u), (eᵘ)' = u'eᵘ, (ln u)' = u'/u, (sin u)' = u'cos u, (cos u)' = −u'sin u. Toujours identifier la fonction extérieure et intérieure."},
  {"deck":"maths","id":"m4j","chapitre":"Dérivation","q":"Comment étudier les variations d'une fonction avec sa dérivée ?","a":"1) Calculer f'(x). 2) Résoudre f'(x)=0 et étudier son signe. 3) Si f'>0 sur I : f croissante sur I. Si f'<0 sur I : f décroissante sur I. 4) En un point x₀ où f' change de signe : extremum local (max si +→−, min si −→+). 5) Dresser le tableau de variations."},
  {"deck":"maths","id":"m4k","chapitre":"Dérivation","q":"Qu'est-ce que la dérivée seconde et à quoi sert-elle ?","a":"f'' = (f')'. Si f''(x)>0 : f est convexe (courbe « en sourire », tangentes en dessous de la courbe). Si f''<0 : concave. Point d'inflexion : f'' change de signe. En un extremum local : si f''(x₀)>0 → minimum ; si f''<0 → maximum. Utile pour optimisation (conditions suffisantes du 2e ordre)."},
  {"deck":"maths","id":"m4l","chapitre":"Dérivation","q":"Comment trouver l'équation de la tangente à une courbe en un point ?","a":"Tangente en x=a : y = f(a) + f'(a)·(x−a). Pente = f'(a). Ex : f(x)=x², a=3 → f(3)=9, f'(3)=6 → tangente : y=9+6(x−3) = 6x−9. Pour une tangente parallèle à y=mx+b : résoudre f'(x)=m puis trouver le point de tangence."},
  {"deck":"maths","id":"m4m","chapitre":"Dérivation","q":"Comment appliquer la dérivation à un problème d'optimisation ?","a":"1) Définir la variable x et la fonction f(x) à maximiser/minimiser. 2) Déterminer le domaine de définition (contraintes). 3) Calculer f'(x). 4) Résoudre f'(x)=0. 5) Étudier le signe de f' pour confirmer nature de l'extremum. 6) Calculer la valeur optimale f(x₀). Toujours vérifier les bornes du domaine."},
  {"deck":"maths","id":"m4n","chapitre":"Dérivation","q":"Quand une fonction est-elle dérivable en un point ?","a":"f est dérivable en a si la limite [f(a+h)−f(a)]/h quand h→0 existe et est finie. Géométriquement : la courbe admet une tangente non verticale en a. Non dérivable si : coin anguleux (|x| en 0), tangente verticale, discontinuité. Une fonction dérivable est continue, mais l'inverse est faux."},
  {"deck":"maths","id":"m4o","chapitre":"Dérivation","q":"Comment dériver une fraction rationnelle u/v ?","a":"(u/v)' = (u'v − uv')/v². Ex : (x²+1)/(2x−1) → u=x²+1, v=2x−1, u'=2x, v'=2. Dérivée = (2x(2x−1) − (x²+1)·2)/(2x−1)² = (4x²−2x−2x²−2)/(2x−1)² = (2x²−2x−2)/(2x−1)². Attention : vérifier v≠0."},

  {"deck":"maths","id":"m5i","chapitre":"Primitives et intégration","q":"Qu'est-ce que la relation entre intégrale et aire ?","a":"∫ₐᵇ f(x)dx représente l'aire algébrique entre la courbe y=f(x) et l'axe Ox, entre x=a et x=b. Algébrique : compte positivement les parties au-dessus de l'axe, négativement les parties en dessous. Pour l'aire géométrique : ∫|f(x)|dx. Découper l'intégrale aux zéros de f."},
  {"deck":"maths","id":"m5j","chapitre":"Primitives et intégration","q":"Quelles sont les primitives des fonctions usuelles ?","a":"xⁿ → xⁿ⁺¹/(n+1) (n≠−1). 1/x → ln|x|. eˣ → eˣ. sin(x) → −cos(x). cos(x) → sin(x). 1/(1+x²) → arctan(x). eᵃˣ → eᵃˣ/a. sin(ax) → −cos(ax)/a. cos(ax) → sin(ax)/a. Ces primitives sont à connaître par cœur."},
  {"deck":"maths","id":"m5k","chapitre":"Primitives et intégration","q":"Comment calculer une intégrale par changement de variable ?","a":"Si on reconnaît ∫g'(x)f(g(x))dx, poser u=g(x), du=g'(x)dx → ∫f(u)du. Ex : ∫2x·eˣ²dx : u=x², du=2xdx → ∫eᵘdu = eᵘ+C = eˣ²+C. Technique : chercher dans l'intégrand une expression et sa dérivée. Très utilisée avec eᵘ, ln(u), u^n."},
  {"deck":"maths","id":"m5l","chapitre":"Primitives et intégration","q":"Comment calculer une intégrale par parties ?","a":"∫u·v'dx = [uv] − ∫u'·v dx. Choisir u qui se simplifie en dérivant, v' qui s'intègre facilement. Ex : ∫x·eˣdx : u=x (u'=1), v'=eˣ (v=eˣ) → [xeˣ] − ∫eˣdx = xeˣ−eˣ+C. Utile pour : x·eˣ, x·sin(x), x·ln(x), ln(x)."},
  {"deck":"maths","id":"m5m","chapitre":"Primitives et intégration","q":"Qu'est-ce que le théorème fondamental de l'analyse ?","a":"Si F est une primitive de f sur [a;b], alors ∫ₐᵇ f(x)dx = F(b)−F(a) = [F(x)]ₐᵇ. Conséquence : la fonction G(x)=∫ₐˣf(t)dt est une primitive de f, et G'(x)=f(x). Ce théorème relie la dérivation et l'intégration (opérations inverses l'une de l'autre)."},
  {"deck":"maths","id":"m5n","chapitre":"Primitives et intégration","q":"Comment calculer l'aire entre deux courbes ?","a":"Aire entre f et g sur [a;b] = ∫ₐᵇ |f(x)−g(x)| dx. Si f(x)≥g(x) sur [a;b] : = ∫ₐᵇ (f(x)−g(x)) dx. Si les courbes se croisent, découper l'intervalle aux points d'intersection et sommer les valeurs absolues. Trouver les intersections en résolvant f(x)=g(x)."},
  {"deck":"maths","id":"m5o","chapitre":"Primitives et intégration","q":"Qu'est-ce qu'une intégrale impropre et comment la calculer ?","a":"Intégrale sur un intervalle infini ou avec une singularité. Ex : ∫₀⁺∞ e⁻ˣdx = lim(b→+∞) ∫₀ᵇ e⁻ˣdx = lim(b→+∞) [−e⁻ˣ]₀ᵇ = lim(b→+∞)(1−e⁻ᵇ) = 1. Converge si la limite existe et est finie. Application : espérance en loi exponentielle, probabilités continues."},

  {"deck":"maths","id":"m6i","chapitre":"Trigonométrie","q":"Quelles sont les valeurs exactes de sin, cos, tan pour les angles remarquables ?","a":"0° : sin=0, cos=1, tan=0. 30° (π/6) : sin=1/2, cos=√3/2, tan=1/√3. 45° (π/4) : sin=cos=√2/2, tan=1. 60° (π/3) : sin=√3/2, cos=1/2, tan=√3. 90° (π/2) : sin=1, cos=0, tan=indéfinie. Mémo : sin croît de 0 à 1 sur [0;π/2]."},
  {"deck":"maths","id":"m6j","chapitre":"Trigonométrie","q":"Quelles sont les formules d'addition cos(a+b) et sin(a+b) ?","a":"cos(a+b) = cos(a)cos(b) − sin(a)sin(b). cos(a−b) = cos(a)cos(b) + sin(a)sin(b). sin(a+b) = sin(a)cos(b) + cos(a)sin(b). sin(a−b) = sin(a)cos(b) − cos(a)sin(b). Cas particulier a=b : cos(2a) = cos²a−sin²a = 1−2sin²a = 2cos²a−1. sin(2a) = 2sin(a)cos(a)."},
  {"deck":"maths","id":"m6k","chapitre":"Trigonométrie","q":"Comment résoudre cos(x) = k ou sin(x) = k ?","a":"cos(x)=k (|k|≤1) : x = ±arccos(k) + 2kπ, k∈ℤ. sin(x)=k (|k|≤1) : x = arcsin(k) + 2kπ ou x = π−arcsin(k) + 2kπ. Sur [0;2π] : localiser les solutions sur le cercle trigonométrique. Ne pas oublier la périodicité (2π pour sin et cos, π pour tan)."},
  {"deck":"maths","id":"m6l","chapitre":"Trigonométrie","q":"Qu'est-ce que la forme trigonométrique Asin(ωt+φ) ?","a":"Tout signal sinusoïdal s'écrit A·sin(ωt+φ) où A=amplitude (max/min), ω=pulsation (rad/s), T=2π/ω=période, f=1/T=fréquence, φ=phase initiale. Pour trouver A et φ à partir de a·sin(x)+b·cos(x) : A=√(a²+b²), tan(φ)=b/a. Utile en physique (circuits, ondes)."},
  {"deck":"maths","id":"m6m","chapitre":"Trigonométrie","q":"Qu'est-ce que la dérivée des fonctions sin et cos ?","a":"(sin x)' = cos x. (cos x)' = −sin x. (tan x)' = 1+tan²x = 1/cos²x. (sin(ax+b))' = a·cos(ax+b). (cos(ax+b))' = −a·sin(ax+b). Applications : étude de f(x)=A·sin(x)+B·cos(x), équations différentielles y''+ω²y=0 (solutions : sin(ωx) et cos(ωx))."},
  {"deck":"maths","id":"m6n","chapitre":"Trigonométrie","q":"Comment convertir entre degrés et radians ?","a":"π radians = 180°. Pour convertir : degrés → radians : multiplier par π/180. Radians → degrés : multiplier par 180/π. Ex : 45° = 45π/180 = π/4 rad. 3π/4 = 135°. Le radian est l'unité naturelle en mathématiques et en physique (arc = rayon × angle en rad)."},
  {"deck":"maths","id":"m6o","chapitre":"Trigonométrie","q":"Quelles sont les identités trigonométriques fondamentales ?","a":"sin²x + cos²x = 1 (relation de Pythagore). tan(x) = sin(x)/cos(x). 1+tan²x = 1/cos²x. cos²x = (1+cos(2x))/2. sin²x = (1−cos(2x))/2. Ces formules permettent de linéariser (remplacer puissances par sin/cos de double angle) et de simplifier des expressions trigonométriques."},

  {"deck":"maths","id":"m7i","chapitre":"Probabilités et statistiques","q":"Qu'est-ce que la loi binomiale B(n,p) et ses paramètres ?","a":"X suit B(n,p) si X = nombre de succès parmi n épreuves de Bernoulli indépendantes, chacune avec probabilité de succès p. P(X=k) = C(n,k)·pᵏ·(1−p)ⁿ⁻ᵏ. Espérance E(X)=np. Variance V(X)=np(1−p). Écart-type σ=√(np(1−p))."},
  {"deck":"maths","id":"m7j","chapitre":"Probabilités et statistiques","q":"Qu'est-ce que la loi normale N(μ,σ²) et ses propriétés ?","a":"Loi continue, courbe en cloche symétrique autour de μ. 68 % des valeurs dans [μ−σ ; μ+σ], 95 % dans [μ−2σ ; μ+2σ], 99,7 % dans [μ−3σ ; μ+3σ]. Loi normale centrée réduite N(0,1) : Z=(X−μ)/σ. Tables ou calculatrice pour P(a<X<b). Approximation de B(n,p) si n grand."},
  {"deck":"maths","id":"m7k","chapitre":"Probabilités et statistiques","q":"Qu'est-ce que la loi des grands nombres et le théorème central limite ?","a":"Loi des grands nombres : la moyenne empirique converge vers E(X) quand n→+∞. TCL : la somme (ou moyenne) de n variables indépendantes identiquement distribuées suit approximativement une loi normale pour n grand (n≥30 en pratique). Justifie l'omniprésence de la loi normale dans les statistiques."},
  {"deck":"maths","id":"m7l","chapitre":"Probabilités et statistiques","q":"Qu'est-ce qu'un intervalle de confiance et comment l'interpréter ?","a":"Intervalle aléatoire contenant le paramètre inconnu (ex : proportion p) avec probabilité 1−α (souvent 95 %). Pour proportion p avec n observations, fréquence f : IC à 95 % ≈ [f−1/√n ; f+1/√n]. Interprétation : sur 100 échantillons, environ 95 intervalles construits contiendraient le vrai p."},
  {"deck":"maths","id":"m7m","chapitre":"Probabilités et statistiques","q":"Comment calculer une probabilité conditionnelle ?","a":"P(A|B) = P(A∩B)/P(B) (avec P(B)>0). Formule de Bayes : P(B|A) = P(A|B)·P(B)/P(A). Formule des probabilités totales : P(A) = Σ P(A|Bᵢ)·P(Bᵢ) pour une partition {B₁,...,Bₙ}. Utile pour : arbres de probabilités, diagnostics médicaux, tests de dépistage."},
  {"deck":"maths","id":"m7n","chapitre":"Probabilités et statistiques","q":"Qu'est-ce que l'espérance et la variance d'une variable aléatoire ?","a":"Espérance E(X) = Σ xᵢ·P(X=xᵢ) (loi discrète). Variance V(X) = E(X²)−[E(X)]² = Σ(xᵢ−μ)²·P(X=xᵢ). Écart-type σ=√V(X). Propriétés : E(aX+b)=aE(X)+b. V(aX+b)=a²V(X). Si X,Y indépendants : E(X+Y)=E(X)+E(Y) et V(X+Y)=V(X)+V(Y)."},
  {"deck":"maths","id":"m7o","chapitre":"Probabilités et statistiques","q":"Comment tester une hypothèse statistique (test d'hypothèse) ?","a":"1) H₀ (hypothèse nulle) vs H₁ (alternative). 2) Choisir statistique de test. 3) Calculer la valeur observée. 4) Comparer à la zone de rejet (seuil α=5 %). 5) Si dans la zone de rejet : rejeter H₀. P-valeur : probabilité d'observer un résultat aussi extrême si H₀ vraie. Si p<α : rejeter H₀."},

  {"deck":"maths","id":"m8i","chapitre":"Géométrie dans l'espace","q":"Quelles sont les formules de volumes des solides usuels ?","a":"Cube (a) : V=a³. Pavé (l,L,h) : V=lLh. Sphère (r) : V=4πr³/3. Cylindre (r,h) : V=πr²h. Cône (r,h) : V=πr²h/3. Pyramide : V=Aire base × h/3. Boule creuse : V=4π(R³−r³)/3. Aire sphère : S=4πr². Latérale cône : S=πrl (l=génératrice)."},
  {"deck":"maths","id":"m8j","chapitre":"Géométrie dans l'espace","q":"Comment utiliser les vecteurs en 3D (produit scalaire) ?","a":"AB→·CD→ = xa·xb + ya·yb + za·zb. |AB| = √(x²+y²+z²). cos(AB,CD) = AB→·CD→ / (|AB|·|CD|). AB⊥CD ⟺ AB→·CD→=0. Le produit scalaire ne donne pas un vecteur mais un scalaire. Utile pour : angles entre vecteurs, orthogonalité, projection."},
  {"deck":"maths","id":"m8k","chapitre":"Géométrie dans l'espace","q":"Qu'est-ce qu'une équation de plan dans l'espace ?","a":"Plan de vecteur normal n=(a,b,c) passant par A(x₀,y₀,z₀) : a(x−x₀)+b(y−y₀)+c(z−z₀)=0, soit ax+by+cz+d=0. Le vecteur (a,b,c) est perpendiculaire au plan. Deux plans sont parallèles si leurs normales sont colinéaires, perpendiculaires si leur produit scalaire est nul."},
  {"deck":"maths","id":"m8l","chapitre":"Géométrie dans l'espace","q":"Comment démontrer que 3 points sont alignés, ou que 4 points sont coplanaires ?","a":"3 points A,B,C alignés : AB→ et AC→ sont colinéaires (AB→=k·AC→, ou det(AB,AC)=0 en 2D). 4 points A,B,C,D coplanaires : AD→ = α·AB→ + β·AC→ pour certains α,β (AD→ est combinaison linéaire de AB et AC). En 3D : det(AB→, AC→, AD→) = 0."},
  {"deck":"maths","id":"m8m","chapitre":"Géométrie dans l'espace","q":"Qu'est-ce que la droite dans l'espace et sa représentation paramétrique ?","a":"Droite passant par A(x₀,y₀,z₀) de vecteur directeur u(a,b,c) : {x=x₀+at, y=y₀+bt, z=z₀+ct, t∈ℝ}. Pour trouver intersection de deux droites : égaliser les paramétrisations et résoudre le système. Si le système n'a pas de solution : droites disjointes (ou parallèles si vecteurs directeurs colinéaires)."},
  {"deck":"maths","id":"m8n","chapitre":"Géométrie dans l'espace","q":"Comment calculer la distance d'un point à un plan ?","a":"Distance de M(x₀,y₀,z₀) au plan ax+by+cz+d=0 : d = |ax₀+by₀+cz₀+d| / √(a²+b²+c²). Ex : distance de O(0,0,0) au plan 2x+y−2z+3=0 : d = |0+0+0+3|/√(4+1+4) = 3/3 = 1. Utile aussi pour la distance entre deux plans parallèles."},
  {"deck":"maths","id":"m8o","chapitre":"Géométrie dans l'espace","q":"Quelles sont les sections d'une sphère et d'un cylindre par un plan ?","a":"Sphère de centre O, rayon R, coupée par un plan à distance d de O : si d<R → cercle de rayon r=√(R²−d²) ; si d=R → point (cercle de rayon 0) ; si d>R → vide. Cylindre coupé perpendiculairement à son axe → cercle. Coupé obliquement → ellipse. Applications : géométrie descriptive, imagerie médicale."},

  # ═══════════════════════════════════════════════════════════════════════
  # SVT
  # ═══════════════════════════════════════════════════════════════════════
  {"deck":"svt","id":"sv1i","chapitre":"ADN et expression du génome","q":"Qu'est-ce que la structure en double hélice de l'ADN ?","a":"Deux brins antiparallèles enroulés en hélice. Chaque brin est une succession de nucléotides (Adénine, Thymine, Guanine, Cytosine + désoxyribose + phosphate). Liaisons hydrogène entre bases complémentaires : A-T (2 liaisons), G-C (3 liaisons). Découverte Watson et Crick (1953) grâce aux travaux de Rosalind Franklin."},
  {"deck":"svt","id":"sv1j","chapitre":"ADN et expression du génome","q":"Qu'est-ce que la réplication de l'ADN et comment se réalise-t-elle ?","a":"Duplication semi-conservative de l'ADN avant la division cellulaire. 1) Ouverture de la double hélice par hélicase. 2) Synthèse du nouveau brin par ADN-polymérase (5'→3') à partir des bases complémentaires. 3) Chaque molécule fille contient un brin parental + un brin néoformé. Erreurs : ~1/10⁹ bases → mutations possibles."},
  {"deck":"svt","id":"sv1k","chapitre":"ADN et expression du génome","q":"Qu'est-ce qu'un gène et un allèle ?","a":"Gène : séquence d'ADN codant pour une protéine ou un ARN fonctionnel. Il occupe un locus précis sur un chromosome. Allèle : version alternative d'un gène (résultant de mutations passées). Ex : gène de la couleur des yeux → allèles « yeux bleus », « yeux marrons ». Les diplôïdes ont 2 allèles par gène (un par chromosome homologue)."},
  {"deck":"svt","id":"sv1l","chapitre":"ADN et expression du génome","q":"Quelles sont les différences entre ARNm, ARNt et ARNr ?","a":"ARNm (messager) : copie du gène, porté par les ribosomes, contient les codons. ARNt (transfert) : apporte l'acide aminé correspondant à un codon (anti-codon). ARNr (ribosomique) : composant structural des ribosomes (centre catalytique). Ces 3 types d'ARN coopèrent lors de la traduction."},
  {"deck":"svt","id":"sv1m","chapitre":"ADN et expression du génome","q":"Qu'est-ce qu'une mutation et quels sont ses effets possibles ?","a":"Modification de la séquence d'ADN. Types : substitution (un nucléotide → autre), insertion, délétion. Effets : mutation silencieuse (code dégénéré → même acide aminé), faux-sens (acide aminé différent), non-sens (codon stop prématuré). Origine : erreur de réplication, UV, agents chimiques. Peut causer maladie génétique, cancer ou avantage sélectif."},
  {"deck":"svt","id":"sv1n","chapitre":"ADN et expression du génome","q":"Comment fonctionne la régulation de l'expression des gènes ?","a":"Tous les gènes ne sont pas exprimés en même temps dans toutes les cellules (même ADN → types cellulaires différents). Régulation : promoteurs (séquences régulatrices avant le gène), facteurs de transcription, méthylation de l'ADN (épigénétique), micro-ARN. Ex : les gènes du foie actifs dans le foie, silencieux dans les neurones."},
  {"deck":"svt","id":"sv1o","chapitre":"ADN et expression du génome","q":"Qu'est-ce que l'épissage de l'ARNpré-messager ?","a":"Chez les eucaryotes, l'ARN pré-messager (transcrit primaire) contient des introns (séquences non codantes) et des exons (séquences codantes). L'épissage = excision des introns + ligature des exons. L'ARNm mature sort du noyau et est traduit. L'épissage alternatif permet à un gène de produire plusieurs protéines différentes."},

  {"deck":"svt","id":"sv2i","chapitre":"Génétique et hérédité","q":"Comment représenter un croisement (P1×P2) et interpréter F1 et F2 ?","a":"P1 (parent 1) × P2 (parent 2) → F1 (1ère génération filiale). Si F1 uniforme : le phénotype exprimé = dominant, l'autre = récessif. F1 × F1 → F2 : ratios attendus 3/4 dominant : 1/4 récessif (monohybridisme). Règle de Mendel : chaque parent transmet un allèle aléatoirement (ségrégation des allèles à la méiose)."},
  {"deck":"svt","id":"sv2j","chapitre":"Génétique et hérédité","q":"Qu'est-ce que la liaison génétique et la recombinaison ?","a":"Deux gènes sur le même chromosome tendent à être transmis ensemble (liés). Mais la recombinaison lors de la méiose (crossing-over) peut séparer des allèles liés. Fréquence de recombinaison ≈ distance génétique (en cM, centimorgans). Si > 50 % de recombinaison : gènes indépendants (même règles que chromosomes différents)."},
  {"deck":"svt","id":"sv2k","chapitre":"Génétique et hérédité","q":"Qu'est-ce que la codominance et la dominance incomplète ?","a":"Dominance incomplète : les deux allèles s'expriment partiellement → phénotype intermédiaire. Ex : rose × blanc → rose pâle. Codominance : les deux allèles s'expriment pleinement et simultanément → phénotype mixte. Ex : groupe sanguin AB (allèles A et B tous les deux exprimés). À distinguer de la dominance complète."},
  {"deck":"svt","id":"sv2l","chapitre":"Génétique et hérédité","q":"Qu'est-ce qu'une maladie génétique autosomique récessive ? Exemple.","a":"Le gène responsable est sur un autosome (non sexuel). L'allèle muté est récessif : seuls les homozygotes (aa) sont malades. Les hétérozygotes (Aa) sont porteurs sains. Ex : mucoviscidose (gène CFTR), phénylcétonurie, albinisme. Parents porteurs sains peuvent avoir un enfant malade (risque 1/4)."},
  {"deck":"svt","id":"sv2m","chapitre":"Génétique et hérédité","q":"Qu'est-ce qu'une maladie génétique liée au chromosome X ?","a":"Le gène muté est sur le chromosome X. Les garçons (XY) n'ont qu'un seul X : ils expriment la maladie si cet X porte l'allèle mutant (hémizygotes). Les filles (XX) peuvent être porteuses sans être malades. Ex : hémophilie, daltonisme. La maladie se transmet principalement par les femmes porteuses à leurs fils."},
  {"deck":"svt","id":"sv2n","chapitre":"Génétique et hérédité","q":"Quels sont les anomalies chromosomiques numériques ?","a":"Trisomie : 3 exemplaires d'un chromosome (2n+1). Trisomie 21 (syndrome de Down) : 3 chromosomes 21, due à non-disjonction lors de la méiose. Monosomie : un seul exemplaire. Syndrome de Turner (45,X) : une seule X chez la femme. Polyploïdie : multiple du génome (rare chez l'Homme, fréquent chez les plantes)."},
  {"deck":"svt","id":"sv2o","chapitre":"Génétique et hérédité","q":"Qu'est-ce que le conseil génétique et le diagnostic prénatal ?","a":"Conseil génétique : évaluation du risque de transmission d'une maladie génétique dans une famille, par un médecin généticien. Diagnostic prénatal : amniocentèse (liquide amniotique, 15-20 SA) ou biopsie de trophoblaste pour analyser l'ADN ou les chromosomes du fœtus. Permet de détecter des anomalies chromosomiques ou génétiques."},

  {"deck":"svt","id":"sv3i","chapitre":"Évolution du vivant","q":"Quels sont les mécanismes de l'évolution selon Darwin et la théorie synthétique ?","a":"Darwin (1859) : sélection naturelle (individus les mieux adaptés se reproduisent davantage). Théorie synthétique (néodarwinisme) : mutation (source de variation), dérive génétique (aléatoire, surtout petites pop.), sélection naturelle (non aléatoire), flux de gènes (migration). Ces 4 mécanismes modifient les fréquences alléliques."},
  {"deck":"svt","id":"sv3j","chapitre":"Évolution du vivant","q":"Qu'est-ce qu'une homologie et une analogie en biologie évolutive ?","a":"Homologie : structures de même origine embryologique, même plan d'organisation, mais fonctions différentes (évolution divergente). Ex : bras humain, nageoire de baleine, aile de chauve-souris → tous issus du même ancêtre. Analogie : structures de même fonction mais d'origines différentes (convergence). Ex : aile d'oiseau et aile d'insecte."},
  {"deck":"svt","id":"sv3k","chapitre":"Évolution du vivant","q":"Qu'est-ce qu'une spéciation et comment se produit-elle ?","a":"Formation d'une nouvelle espèce à partir d'une espèce ancestrale. Spéciation allopatrique (géographique) : isolement physique d'une population → accumulation de différences génétiques → incapacité à se reproduire ensemble. Spéciation sympatrique : dans la même zone, isolement reproductif par d'autres mécanismes (comportement, ploïdie)."},
  {"deck":"svt","id":"sv3l","chapitre":"Évolution du vivant","q":"Qu'est-ce qu'un arbre phylogénétique et comment le lire ?","a":"Représentation des relations de parenté entre espèces, basée sur des caractères partagés (synapomorphies). Nœuds = ancêtres communs. Plus le nœud est récent, plus les espèces sont proches. Les espèces sur un même embranchement partagent un ancêtre commun exclusif (clade ou groupe monophylétique)."},
  {"deck":"svt","id":"sv3m","chapitre":"Évolution du vivant","q":"Qu'est-ce que la dérive génétique et son impact sur les populations ?","a":"Variation aléatoire des fréquences alléliques au fil des générations, due au hasard de la reproduction (surtout dans les petites populations). Peut fixer un allèle (fréquence=1) ou en éliminer un (fréquence=0) par pur hasard. Effet fondateur : petite population fonde un nouvel habitat → perd de la diversité génétique."},
  {"deck":"svt","id":"sv3n","chapitre":"Évolution du vivant","q":"Quelles sont les preuves de l'évolution (fossiles, biologie moléculaire) ?","a":"Fossiles : transitions entre espèces (ex : Archaeopteryx entre dinosaures et oiseaux). Anatomie comparée : homologies. Biologie moléculaire : comparaison des séquences d'ADN/protéines (cytochrome c, ADNmt) → distance génétique = durée de séparation. Embryologie comparée. Exemples d'évolution observable en temps réel (bactéries, pinsons des Galápagos)."},
  {"deck":"svt","id":"sv3o","chapitre":"Évolution du vivant","q":"Qu'est-ce que la coévolution et le mutualisme ?","a":"Coévolution : deux espèces évoluent ensemble en réponse à leurs interactions réciproques. Ex : fleurs et pollinisateurs (orchidées et abeilles), parasites et hôtes (course aux armements). Mutualisme : interaction bénéfique pour les deux espèces. Ex : mycorhizes (champignon + racine), bactéries intestinales + hôte humain, légumineuses + Rhizobium fixateur d'azote."},

  {"deck":"svt","id":"sv4i","chapitre":"Métabolisme cellulaire","q":"Qu'est-ce que la glycolyse et où se déroule-t-elle ?","a":"Première étape de la respiration cellulaire, dans le cytoplasme. Dégradation du glucose (6C) en 2 pyruvates (3C). Bilan : 1 glucose → 2 pyruvates + 2 ATP + 2 NADH. Ne nécessite pas d'O₂. Les pyruvates entrent ensuite dans les mitochondries (si O₂ présent) ou sont transformés en lactate/éthanol (fermentation, sans O₂)."},
  {"deck":"svt","id":"sv4j","chapitre":"Métabolisme cellulaire","q":"Qu'est-ce que le cycle de Krebs (cycle de l'acide citrique) ?","a":"Dans la matrice mitochondriale. Chaque pyruvate → acétyl-CoA (2C) + CO₂. L'acétyl-CoA entre dans le cycle, produisant CO₂, NADH, FADH₂ et ATP. Bilan par glucose : 2 tours du cycle → 6 CO₂ + 8 NADH + 2 FADH₂ + 2 ATP. Ces coenzymes (NADH, FADH₂) portent les électrons vers la chaîne respiratoire."},
  {"deck":"svt","id":"sv4k","chapitre":"Métabolisme cellulaire","q":"Comment fonctionne la photosynthèse en deux phases ?","a":"Phase lumineuse (thylakoïdes) : absorption lumière par chlorophylle → excitation électrons → production ATP + NADPH + O₂ (photolyse de l'eau). Phase sombre/Calvin (stroma) : fixation du CO₂ par RuBisCO + utilisation ATP et NADPH → production glucose (G3P). Bilan : 6CO₂+6H₂O+lumière → C₆H₁₂O₆+6O₂."},
  {"deck":"svt","id":"sv4l","chapitre":"Métabolisme cellulaire","q":"Qu'est-ce que la fermentation lactique et alcoolique ?","a":"Fermentation lactique (muscles, bactéries) : pyruvate → lactate + régénération NAD⁺. Fermentation alcoolique (levures) : pyruvate → éthanol + CO₂ + régénération NAD⁺. Les deux sont anaérobies (sans O₂). Permettent de régénérer le NAD⁺ pour continuer la glycolyse quand l'O₂ manque. Bilan énergetique faible (2 ATP seulement)."},
  {"deck":"svt","id":"sv4m","chapitre":"Métabolisme cellulaire","q":"Qu'est-ce qu'une enzyme et comment fonctionne-t-elle ?","a":"Protéine catalysant une réaction biochimique spécifique. Le substrat se fixe sur le site actif (complémentarité de forme et chimique). Paramètres : température optimale (~37°C pour les enzymes humaines), pH optimal, Km (affinité), Vmax (vitesse maximale). Inhibiteurs compétitifs (bloquent le site actif) ou non compétitifs. Ne sont pas consommées."},
  {"deck":"svt","id":"sv4n","chapitre":"Métabolisme cellulaire","q":"Qu'est-ce que l'ATP et son rôle dans la cellule ?","a":"Adénosine triphosphate = molécule universelle de transfert d'énergie. Hydrolyse ATP → ADP + Pi libère ~30 kJ/mol utilisés pour les réactions endergoniques (synthèse, transport actif, mouvement musculaire). La cellule régénère l'ATP à partir d'ADP : respiration cellulaire (~36-38 ATP/glucose), fermentation (2 ATP/glucose), photosynthèse."},
  {"deck":"svt","id":"sv4o","chapitre":"Métabolisme cellulaire","q":"Qu'est-ce que la chaîne respiratoire mitochondriale ?","a":"Membrane interne de la mitochondrie. Les électrons de NADH et FADH₂ passent par des complexes protéiques (NADH déshydrogénase, cytochrome bc1, cytochrome oxydase), réduisant O₂ en H₂O. Ce transfert pompe des H⁺ hors de la matrice → gradient proton → ATP synthase produit ATP (chimiosmose). Bilan : ~32-34 ATP/glucose."},

  {"deck":"svt","id":"sv5i","chapitre":"Le système nerveux","q":"Qu'est-ce qu'un potentiel d'action et comment se propage-t-il ?","a":"Signal électrique court (~1 ms) se propageant le long de l'axone. Phase dépolarisation : canaux Na⁺ s'ouvrent → Na⁺ entre (−70 mV → +40 mV). Phase repolarisation : canaux K⁺ s'ouvrent → K⁺ sort → retour potentiel de repos. Propagation unidirectionnelle grâce à la période réfractaire. Myéline accélère la propagation (conduction saltatoire)."},
  {"deck":"svt","id":"sv5j","chapitre":"Le système nerveux","q":"Qu'est-ce qu'une synapse chimique et comment fonctionne-t-elle ?","a":"Zone de contact entre deux neurones. L'influx nerveux dans le neurone présynaptique → libération de neurotransmetteurs (dopamine, sérotonine, acétylcholine, glutamate…) dans la fente synaptique. Les neurotransmetteurs se fixent sur des récepteurs du neurone postsynaptique → dépolarisation (synapse excitatrice) ou hyperpolarisation (inhibitrice)."},
  {"deck":"svt","id":"sv5k","chapitre":"Le système nerveux","q":"Quelle est la différence entre SNP somatique et végétatif ?","a":"SNP somatique : contrôle volontaire des muscles squelettiques. SNP végétatif (autonome) : contrôle inconscient des organes internes (cœur, intestins, glandes). Divisé en : système sympathique (adrénaline, réponse stress → « fight or flight ») et parasympathique (acétylcholine, repos/digestion → « rest and digest »). Ces deux systèmes ont des effets antagonistes."},
  {"deck":"svt","id":"sv5l","chapitre":"Le système nerveux","q":"Quelles sont les grandes fonctions du cortex cérébral ?","a":"Cortex frontal : fonctions exécutives (planification, jugement), motricité volontaire. Cortex pariétal : intégration sensorielle, espace. Cortex temporal : mémoire, langage (aire de Wernicke), audition. Cortex occipital : vision. Aire de Broca (frontal gauche) : production du langage. IRM fonctionnelle révèle l'activité de zones spécifiques selon les tâches."},
  {"deck":"svt","id":"sv5m","chapitre":"Le système nerveux","q":"Qu'est-ce qu'un arc réflexe et quelle est sa voie nerveuse ?","a":"Voie nerveuse permettant une réponse automatique et rapide sans décision consciente. Récepteur sensoriel → neurone afférent (sensitif) → centre d'intégration (moelle épinière) → neurone efférent (moteur) → effecteur (muscle). Ex : réflexe rotulien (marteau). La voie passe par la moelle sans remonter au cerveau → très rapide."},
  {"deck":"svt","id":"sv5n","chapitre":"Le système nerveux","q":"Quels sont les effets de drogues sur les synapses ?","a":"Les drogues agissent sur les synapses : cocaïne bloque la recapture de dopamine → excès dopamine dans la fente. Héroïne imite les endorphines sur leurs récepteurs. Alcool potentialise l'inhibition GABA. Cannabis imite les endocannabinoïdes. Ces substances détournent le système de récompense (circuit mésolimbique dopaminergique) → addiction."},
  {"deck":"svt","id":"sv5o","chapitre":"Le système nerveux","q":"Qu'est-ce que la plasticité synaptique et son rôle dans la mémoire ?","a":"La force des synapses peut être renforcée (LTP, potentialisation à long terme) ou affaiblie (LTD). La LTP : stimulation répétée d'une synapse → plus de récepteurs AMPA → transmission plus efficace. Base cellulaire de l'apprentissage et de la mémoire. « Des neurones qui s'activent ensemble se connectent ensemble » (Hebb). L'hippocampe est crucial pour la mémoire déclarative."},

  {"deck":"svt","id":"sv6i","chapitre":"Le système immunitaire","q":"Quelles sont les deux lignes de défense immunitaires non spécifiques ?","a":"1ère ligne (barrières physiques et chimiques) : peau, muqueuses, larmes, salive, pH acide de l'estomac. 2ème ligne (immunité innée) : phagocytose (neutrophiles, macrophages) englobent les pathogènes, inflammation, protéines du complément, cellules NK (tuent les cellules infectées). Rapide mais non spécifique : réagit à tout pathogène."},
  {"deck":"svt","id":"sv6j","chapitre":"Le système immunitaire","q":"Qu'est-ce qu'un anticorps et comment neutralise-t-il un pathogène ?","a":"Glycoprotéine en forme de Y produite par les plasmocytes (lymphocytes B activés). Composée de 2 chaînes lourdes + 2 chaînes légères. Site de fixation à l'antigène : variable (spécifique). Mécanismes : neutralisation (bloque les sites actifs du pathogène), opsonisation (facilite la phagocytose), activation du complément. 5 classes : IgG, IgM, IgA, IgE, IgD."},
  {"deck":"svt","id":"sv6k","chapitre":"Le système immunitaire","q":"Comment fonctionne un vaccin et qu'est-ce que l'immunité de groupe ?","a":"Vaccin : antigène atténué/inactivé/fragment → stimule une réponse primaire → mémoire immunitaire → réponse secondaire rapide et intense si vrai pathogène. Immunité de groupe : si >90-95 % de la population est immunisée, le virus ne trouve pas assez d'hôtes → protection des personnes non vaccinées. Seuil selon le R₀ du pathogène."},
  {"deck":"svt","id":"sv6l","chapitre":"Le système immunitaire","q":"Qu'est-ce qu'une maladie auto-immune et comment se développe-t-elle ?","a":"Le système immunitaire attaque les cellules du soi. Ex : diabète de type 1 (attaque des cellules β du pancréas), sclérose en plaques (attaque de la myéline), polyarthrite rhumatoïde (articulations), lupus. Cause : perte de la tolérance au soi (défaut d'élimination des lymphocytes auto-réactifs). Traitements : immunosuppresseurs."},
  {"deck":"svt","id":"sv6m","chapitre":"Le système immunitaire","q":"Qu'est-ce que l'immunité à médiation cellulaire (lymphocytes T) ?","a":"Lymphocytes T cytotoxiques (CD8⁺) : détruisent directement les cellules infectées ou cancéreuses en induisant leur apoptose. Lymphocytes T auxiliaires (CD4⁺, T helper) : coordonnent la réponse immunitaire (stimulent B et T cytotoxiques via cytokines, notamment interleukines). Le VIH détruit les CD4⁺ → effondrement de l'immunité."},
  {"deck":"svt","id":"sv6n","chapitre":"Le système immunitaire","q":"Qu'est-ce que l'inflammation et la réaction fébrile ?","a":"Inflammation : vasodilatation + afflux de phagocytes sur le site d'infection → chaleur, rougeur, gonflement, douleur. Médiateurs : histamine, prostaglandines, cytokines. Fièvre : les pyrogènes (cytokines IL-1, IL-6, TNF) agissent sur l'hypothalamus → hausse du thermostat → T° corporelle augmente → ralentit la croissance bactérienne, accélère les réponses immunitaires."},
  {"deck":"svt","id":"sv6o","chapitre":"Le système immunitaire","q":"Comment fonctionne la présentation de l'antigène (CMH) ?","a":"Le Complexe Majeur d'Histocompatibilité (CMH) présente des fragments de protéines (peptides) à la surface des cellules. CMH de classe I (toutes les cellules) présente des peptides intracellulaires aux CD8⁺. CMH de classe II (cellules présentatrices d'antigènes : macrophages, dendritiques, B) présente des antigènes extracellulaires aux CD4⁺. Permet la reconnaissance du « soi modifié »."},

  {"deck":"svt","id":"sv7i","chapitre":"Écologie et enjeux environnementaux","q":"Qu'est-ce qu'un écosystème et comment fonctionne-t-il ?","a":"Ensemble formé par une communauté d'êtres vivants (biocénose) et son milieu non vivant (biotope). Les organismes interagissent entre eux et avec leur milieu via les flux de matière et d'énergie. Niveaux trophiques : producteurs (plantes) → consommateurs primaires → secondaires → tertiaires → décomposeurs. L'énergie se perd à chaque niveau (~90 %)."},
  {"deck":"svt","id":"sv7j","chapitre":"Écologie et enjeux environnementaux","q":"Qu'est-ce que la biodiversité et ses 3 niveaux ?","a":"1) Diversité des écosystèmes (forêts, récifs, toundra…). 2) Diversité spécifique (nombre d'espèces dans un milieu). 3) Diversité génétique (variabilité allélique au sein d'une population). La biodiversité rend les écosystèmes stables et résilients. Elle fournit des services écosystémiques (pollinisation, purification de l'eau, alimentation, médicaments)."},
  {"deck":"svt","id":"sv7k","chapitre":"Écologie et enjeux environnementaux","q":"Quels sont les impacts du changement climatique sur les écosystèmes ?","a":"• Acidification des océans (absorption CO₂ → H₂CO₃) → coraux dissous\n• Décalage des saisons → désynchronisation floraison/pollinisateurs\n• Migration des espèces vers les pôles et en altitude\n• Blanchissement des coraux (stress thermique)\n• Extinction d'espèces : ~1 million d'espèces menacées (IPBES 2019)\n• Perturbation des migrations d'oiseaux"},
  {"deck":"svt","id":"sv7l","chapitre":"Écologie et enjeux environnementaux","q":"Qu'est-ce que le cycle du carbone et le rôle des océans ?","a":"Réservoirs : atmosphère (CO₂), biosphère, lithosphère (combustibles fossiles), hydrosphère (carbonate). Flux naturels : photosynthèse (fixation), respiration/décomposition (libération), weathering (érosion des roches). Les océans absorbent ~25 % du CO₂ anthropique → s'acidifient. La déforestation libère du carbone stocké. Perturbation anthropique → accumulation CO₂ atmosphérique."},
  {"deck":"svt","id":"sv7m","chapitre":"Écologie et enjeux environnementaux","q":"Qu'est-ce que les services écosystémiques et leur valeur économique ?","a":"Services fournis par les écosystèmes : approvisionnement (nourriture, eau, bois, médicaments), régulation (climat, purification eau, pollinisation, prévention crues), culturels (loisirs, spiritualité), soutien (formation des sols, cycles biogéochimiques). La pollinisation vaut ~150-200 Mds€/an pour l'agriculture mondiale. Leur destruction représente un coût économique énorme."},
  {"deck":"svt","id":"sv7n","chapitre":"Écologie et enjeux environnementaux","q":"Quels sont les principaux facteurs de la 6e extinction de masse ?","a":"Les 5 causes principales (acronyme HIPPO) : Habitat destruction (déforestation, urbanisation), Invasive species (espèces invasives), Pollution, Population humaine (surexploitation), Overexploitation (chasse, pêche). Le changement climatique s'y ajoute comme 6e facteur. Taux d'extinction actuel : 100 à 1000 fois supérieur au taux naturel de fond."},
  {"deck":"svt","id":"sv7o","chapitre":"Écologie et enjeux environnementaux","q":"Qu'est-ce que l'empreinte écologique et le jour du dépassement ?","a":"Empreinte écologique : surface de terre et de mer nécessaire pour fournir les ressources consommées par un individu/pays. Si > biocapacité planétaire → déficit écologique. Le Jour du dépassement (Earth Overshoot Day) : date à laquelle l'humanité a consommé les ressources renouvelables de la planète pour l'année. En 2024 : ~1er août. La France aurait besoin de 2,9 planètes."},

  {"deck":"svt","id":"sv8i","chapitre":"Tectonique des plaques","q":"Qu'est-ce que la dorsale océanique et quel phénomène s'y produit ?","a":"Chaîne de montagnes sous-marines (~70 000 km) où du magma remonte depuis le manteau, refroidit et forme un nouveau plancher océanique (expansion des fonds océaniques). La lave forme des « pillow lavas ». Les plaques s'écartent (divergence) : ~2-20 cm/an. Dorsale médio-atlantique : l'Europe et l'Amérique s'éloignent de ~2,5 cm/an."},
  {"deck":"svt","id":"sv8j","chapitre":"Tectonique des plaques","q":"Qu'est-ce qu'une zone de subduction et quels phénomènes s'y produisent ?","a":"Zone où une plaque océanique (dense) plonge sous une autre plaque (continentale ou océanique). La plaque subduite fond dans le manteau → magma → volcans en chapelet au-dessus. Fosses océaniques très profondes (Mariannes, 11 km). Tremblements de terre violents (Japon, Chili). Ex : Cercle de feu du Pacifique = ceinture de subductions."},
  {"deck":"svt","id":"sv8k","chapitre":"Tectonique des plaques","q":"Comment les séismes sont-ils générés et mesurés ?","a":"Séisme : rupture soudaine d'une faille sous l'effet de la pression tectonique. Foyer (hypocentre) : point de rupture en profondeur. Épicentre : point en surface au-dessus. Ondes sismiques : P (compression, plus rapides), S (cisaillement), L et R (surface). Richter (magnitude) : logarithmique (chaque niveau = ×10 en amplitude). Mercalli : dégâts observés."},
  {"deck":"svt","id":"sv8l","chapitre":"Tectonique des plaques","q":"Comment les preuves paléomagnétiques soutiennent-elles la tectonique des plaques ?","a":"En se solidifiant, les basaltes des dorsales enregistrent la polarité du champ magnétique terrestre de l'époque. Le champ s'est inversé plusieurs fois. On observe des bandes magnétiques symétriques de part et d'autre des dorsales → preuve de l'expansion des fonds océaniques. Datation des bandes → vitesse de divergence des plaques."},
  {"deck":"svt","id":"sv8m","chapitre":"Tectonique des plaques","q":"Qu'est-ce qu'une collision continentale et quelles formations en résultent ?","a":"Quand deux plaques continentales entrent en collision, aucune ne subducte (trop légères). Les sédiments se plissent et s'épaississent → chaîne de montagne. Ex : Himalaya (Inde + Eurasie, collision depuis 50 Ma, toujours en cours → +5 mm/an). Alpes (Afrique + Europe). Des fossiles marins se trouvent en altitude : preuve que ces zones étaient sous la mer."},
  {"deck":"svt","id":"sv8n","chapitre":"Tectonique des plaques","q":"Qu'est-ce qu'un point chaud et comment explique-t-il les îles volcaniques en chapelet ?","a":"Panache de magma très chaud fixe dans le manteau, indépendant des frontières de plaques. La plaque se déplace au-dessus → volcans successifs qui s'éteignent en s'éloignant du point chaud. Ex : archipel d'Hawaï : île de Hawaï (active) → Maui → Oahu → Kauai (de plus en plus vieux vers le NO). Révèle la direction et la vitesse de déplacement de la plaque Pacifique."},
  {"deck":"svt","id":"sv8o","chapitre":"Tectonique des plaques","q":"Qu'est-ce que le cycle de Wilson et l'histoire des océans ?","a":"Cycle de ~500 Ma décrivant l'ouverture et la fermeture des océans. Stades : rifting continental (fracture) → océan naissant (mer Rouge) → océan adulte (Atlantique) → subduction → fermeture et collision (Himalaya). Toutes les 500 Ma, les continents se regroupent en supercontinent (Pangée) puis se dispersent. Preuve : roches océaniques jamais plus vieilles que 200 Ma."},

  # ═══════════════════════════════════════════════════════════════════════
  # PHYSIQUE-CHIMIE
  # ═══════════════════════════════════════════════════════════════════════
  {"deck":"physique","id":"ph1i","chapitre":"Mécanique — Lois du mouvement","q":"Comment appliquer la 2e loi de Newton à un objet en chute libre ?","a":"Forces : poids P=mg↓, résistance de l'air (si négligée). Σ F = mg = ma → a = g ≈ 9,8 m/s². Équations horaires : v(t) = v₀ + gt. z(t) = z₀ + v₀t + ½gt². Si lancé verticalement vers le haut (v₀>0) : le signe de g est négatif (axe vers le haut) → décélération puis chute. Point le plus haut : v=0, t=v₀/g."},
  {"deck":"physique","id":"ph1j","chapitre":"Mécanique — Lois du mouvement","q":"Qu'est-ce qu'un référentiel et pourquoi est-il important en mécanique ?","a":"Ensemble de points de référence par rapport auquel on décrit le mouvement. Référentiels courants : terrestre (pour mouvements courants), géocentrique (satellites), héliocentrique (planètes). Un mouvement est RELATIF au référentiel choisi. Principe d'inertie valable seulement dans les référentiels galiléens (en translation rectiligne uniforme par rapport aux étoiles fixes)."},
  {"deck":"physique","id":"ph1k","chapitre":"Mécanique — Lois du mouvement","q":"Qu'est-ce que la 3e loi de Newton (action-réaction) ?","a":"Toute force exercée par A sur B est accompagnée d'une force exercée par B sur A, égale et opposée : F(A→B) = −F(B→A). Ces forces s'appliquent sur des objets différents (donc ne se compensent pas). Ex : poids de la Terre sur vous → vous exercez une force égale sur la Terre (mais la Terre ne bouge presque pas car sa masse est immense)."},
  {"deck":"physique","id":"ph1l","chapitre":"Mécanique — Lois du mouvement","q":"Qu'est-ce que le mouvement circulaire uniforme et son accélération ?","a":"Mouvement sur un cercle à vitesse constante en valeur. La vitesse change de direction → accélération centripète (vers le centre) : a = v²/R = ω²R. La force centripète : F = mv²/R. Période T = 2πR/v = 2π/ω. Ex : satellite circulaire, voiture dans un virage. La force centripète n'est pas une nouvelle force mais la composante centripète de la résultante."},
  {"deck":"physique","id":"ph1m","chapitre":"Mécanique — Lois du mouvement","q":"Qu'est-ce qu'un tir parabolique (projectile) ?","a":"Mouvement sous l'effet du seul poids (sans frottement). Décomposer en 2 : horizontal : Fx=0 → MRU, x=v₀cos(θ)·t. Vertical : Fy=−mg → MRUA, y=v₀sin(θ)·t−½gt². La trajectoire est une parabole. Portée maximale à 45°. Indépendance des mouvements horizontal et vertical (principe de superposition)."},
  {"deck":"physique","id":"ph1n","chapitre":"Mécanique — Lois du mouvement","q":"Qu'est-ce que la loi de gravitation universelle (Newton) ?","a":"Toute masse attire toute autre masse : F = G·m₁·m₂/d². G = 6,67×10⁻¹¹ N·m²/kg². g en surface = GM_Terre/R_Terre² ≈ 9,8 m/s². G définit l'orbite des satellites : GMm/r² = mv²/r → v = √(GM/r). Cette loi explique les marées, les orbites planétaires, la forme sphérique des astres."},
  {"deck":"physique","id":"ph1o","chapitre":"Mécanique — Lois du mouvement","q":"Comment analyser un système de plusieurs forces (équilibre) ?","a":"Un solide est en équilibre si : 1) ΣF=0 (somme vectorielle des forces nulle) ET 2) Σmoments=0 (les forces ne font pas tourner). Méthode : dresser l'inventaire des forces (poids, réactions normales, frottements, tension…), décomposer sur les axes, écrire les équations. Ex : boule sur plan incliné : P + R_normale + frottement = 0."},

  {"deck":"physique","id":"ph2i","chapitre":"Mécanique — Travail et énergie","q":"Qu'est-ce que le travail d'une force constante ?","a":"W = F·d·cos(α) où α est l'angle entre F et le déplacement d. Unité : joule (J). W>0 si la force « aide » le mouvement (moteur). W<0 si elle s'y oppose (résistant). W=0 si force perpendiculaire au déplacement (force normale d'un plan horizontal). Le poids sur un déplacement vertical : W(P) = mgΔh (positif si descente)."},
  {"deck":"physique","id":"ph2j","chapitre":"Mécanique — Travail et énergie","q":"Qu'est-ce que la puissance et comment est-elle liée au travail ?","a":"P = W/t (puissance moyenne) ou P = F·v (puissance instantanée). Unité : watt (W = J/s). 1 ch (cheval-vapeur) ≈ 736 W. Le rendement η = P_utile/P_consommée (0 < η ≤ 1). Ex : voiture de 100 kW à 130 km/h → puissance consommée > 100 kW (frottements). Les kWh sont des unités d'énergie (1 kWh = 3,6 MJ)."},
  {"deck":"physique","id":"ph2k","chapitre":"Mécanique — Travail et énergie","q":"Qu'est-ce que l'énergie potentielle gravitationnelle et comment évolue-t-elle ?","a":"Ep = mgh (référence au sol h=0). Augmente quand l'objet monte (travail contre la gravité), diminue quand il descend. Convertie en énergie cinétique lors de la chute : si pas de frottements, Ep+Ec = constante (conservation de l'énergie mécanique). Ex : bille lancée vers le haut : Ec max en bas ↔ Ep max en haut."},
  {"deck":"physique","id":"ph2l","chapitre":"Mécanique — Travail et énergie","q":"Comment s'applique la conservation de l'énergie avec des frottements ?","a":"Avec frottements : Em finale = Em initiale − |W_frottements|. L'énergie mécanique diminue ; l'énergie dissipée en chaleur = |W_frottements|. Bilan énergétique global : l'énergie totale est conservée (1er principe de thermodynamique) — elle change seulement de forme (mécanique → thermique). Les frottements ne créent pas ni ne détruisent d'énergie."},
  {"deck":"physique","id":"ph2m","chapitre":"Mécanique — Travail et énergie","q":"Qu'est-ce que l'énergie cinétique de rotation ?","a":"Ec_rot = ½Iω² où I est le moment d'inertie (analogue de la masse pour la rotation) et ω la vitesse angulaire. Pour une sphère : I=2mr²/5. Un corps en rotation possède une énergie cinétique de rotation en plus de son énergie cinétique de translation. Ex : la Terre tourne → Ec_rot ≈ 2,6×10²⁹ J."},
  {"deck":"physique","id":"ph2n","chapitre":"Mécanique — Travail et énergie","q":"Qu'est-ce que la conservation de la quantité de mouvement ?","a":"p = mv (quantité de mouvement). Si la somme des forces extérieures est nulle : Σp = cste (conservation). Utile pour les chocs : choc élastique (Ec et p conservées) vs choc inélastique (seule p conservée, Ec diminue — convertie en déformation, chaleur). Ex : boules de billard, accident de voiture, propulsion de fusée."},
  {"deck":"physique","id":"ph2o","chapitre":"Mécanique — Travail et énergie","q":"Comment calculer le travail des forces dans un problème sur plan incliné ?","a":"Plan incliné d'angle θ, masse m, longueur L. W(poids) = mg·L·sin(θ) (composante du poids le long du plan). W(normale) = 0 (perpendiculaire au déplacement). W(frottement) = −f·L (f=μ·mg·cos(θ), μ = coefficient de frottement). Bilan : Ec finale = Ec initiale + W(poids) + W(frottement)."},

  {"deck":"physique","id":"ph3i","chapitre":"Ondes mécaniques et sonores","q":"Qu'est-ce que la longueur d'onde et comment est-elle reliée à la fréquence ?","a":"λ = v/f. λ (lambda) = longueur d'onde (m), v = vitesse de propagation (m/s), f = fréquence (Hz). Dans l'air à 20°C : v_son ≈ 340 m/s. Ex : La = 440 Hz → λ = 340/440 ≈ 0,77 m. Plus la fréquence est élevée, plus la longueur d'onde est courte. La longueur d'onde ne change pas avec le milieu : c'est la vitesse qui change."},
  {"deck":"physique","id":"ph3j","chapitre":"Ondes mécaniques et sonores","q":"Qu'est-ce que l'effet Doppler ?","a":"Changement apparent de fréquence d'une onde quand la source ou l'observateur se déplacent. Si la source s'approche : fréquence apparente augmente (son aigu). Si elle s'éloigne : fréquence diminue (grave). f' = f·(v±v_obs)/(v∓v_source). Applications : radar de vitesse, échographie médicale (Doppler vasculaire), détection d'exoplanètes (décalage spectral)."},
  {"deck":"physique","id":"ph3k","chapitre":"Ondes mécaniques et sonores","q":"Qu'est-ce qu'une onde stationnaire et comment se forme-t-elle ?","a":"Superposition de deux ondes de même fréquence se propageant en sens opposés. Résultat : nœuds (points toujours immobiles) et ventres (oscillation maximale) fixes dans l'espace. Formation dans les instruments de musique (corde de guitare, colonne d'air de flûte). Condition : L = n·λ/2 (harmoniques). Le son produit dépend des harmoniques excités."},
  {"deck":"physique","id":"ph3l","chapitre":"Ondes mécaniques et sonores","q":"Comment mesure-t-on le niveau sonore et l'échelle des décibels ?","a":"Niveau sonore L (dB) = 10·log(I/I₀) où I₀=10⁻¹² W/m² (seuil d'audition). Échelle logarithmique : +10 dB → intensité ×10 ; +3 dB → ×2. Exemples : 0 dB (silence absolu), 60 dB (conversation), 120 dB (concert, seuil douleur), 140 dB (réacteur d'avion). Au-delà de 85 dB prolongé → risque de surdité."},
  {"deck":"physique","id":"ph3m","chapitre":"Ondes mécaniques et sonores","q":"Qu'est-ce que la diffraction des ondes ?","a":"Contournement d'un obstacle ou élargissement d'une onde après passage par une ouverture. Importante si la longueur d'onde λ est comparable aux dimensions de l'obstacle/ouverture. Modèle : les vibrations à l'ouverture deviennent de nouvelles sources (principe de Huygens). Ex : son contourne les murs, radio grandes ondes contourne les collines, lumière visible ne diffracte pas facilement (λ très petite)."},
  {"deck":"physique","id":"ph3n","chapitre":"Ondes mécaniques et sonores","q":"Qu'est-ce que les ondes transversales vs longitudinales ?","a":"Transversales : oscillation perpendiculaire à la direction de propagation. Ex : cordes, ondes électromagnétiques, ondes S sismiques. Longitudinales : oscillation parallèle à la direction de propagation. Ex : son (variations de pression), ondes P sismiques, ressort comprimé-étiré. Le son dans l'air est une onde de pression longitudinale."},
  {"deck":"physique","id":"ph3o","chapitre":"Ondes mécaniques et sonores","q":"Comment calculer la vitesse du son dans différents milieux ?","a":"Le son se propage par oscillation des particules du milieu. Vitesse ≈ 340 m/s dans l'air (20°C), ~1 480 m/s dans l'eau, ~5 000 m/s dans l'acier. Plus le milieu est rigide et dense (rapport élasticité/densité), plus le son va vite. Le son ne se propage pas dans le vide (pas de matière à faire vibrer). v_air augmente avec T : v ≈ 331 + 0,6·T°C."},

  {"deck":"physique","id":"ph4i","chapitre":"Optique — Lumière et lentilles","q":"Qu'est-ce que l'indice de réfraction et comment calcule-t-on la réfraction ?","a":"n = c/v où c = 3×10⁸ m/s (lumière dans le vide), v = vitesse dans le milieu. Loi de Snell-Descartes : n₁·sin(i₁) = n₂·sin(i₂). Si n₂>n₁ (milieu plus dense) : le rayon se rapproche de la normale (i₂<i₁). Ex : eau (n=1,33), verre (n=1,5), air (n=1). La réfraction explique l'aspect brisé d'une cuillère dans l'eau."},
  {"deck":"physique","id":"ph4j","chapitre":"Optique — Lumière et lentilles","q":"Qu'est-ce que la réflexion totale interne et ses applications ?","a":"Si l'angle d'incidence dépasse l'angle limite (sin(i_limite) = n₂/n₁, avec n₁>n₂) : la lumière ne sort plus du milieu — réflexion totale. Applications : fibre optique (lumière guidée sur des milliers de km sans perte), prismes (déviation à 90° ou 180°), endoscope médical. Condition : aller d'un milieu dense vers un milieu moins dense."},
  {"deck":"physique","id":"ph4k","chapitre":"Optique — Lumière et lentilles","q":"Qu'est-ce que la dispersion de la lumière blanche par un prisme ?","a":"La lumière blanche est un mélange de toutes les longueurs d'onde du visible (380-700 nm). L'indice de réfraction d'un matériau dépend de λ (plus petit pour le rouge, plus grand pour le violet). Donc le prisme dévie différemment chaque couleur → arc-en-ciel artificiel (ROYGBIV). L'arc-en-ciel naturel est produit par les gouttes d'eau qui agissent comme des prismes."},
  {"deck":"physique","id":"ph4l","chapitre":"Optique — Lumière et lentilles","q":"Comment construire l'image d'un objet à travers une lentille convergente ?","a":"3 rayons particuliers : 1) Passant par le centre optique → non dévié. 2) Parallèle à l'axe → passe par F'. 3) Passant par F → ressort parallèle à l'axe. L'image est à l'intersection des 3 rayons. Si objet avant F (p>f) : image réelle, renversée, de l'autre côté. Si objet entre F et O (p<f) : image virtuelle, droite, agrandie (loupe)."},
  {"deck":"physique","id":"ph4m","chapitre":"Optique — Lumière et lentilles","q":"Qu'est-ce que le spectre électromagnétique (de radio à rayons gamma) ?","a":"Ondes radio (λ>1m) → micro-ondes → infrarouge → visible (380-700 nm) → UV → rayons X → rayons gamma (λ<0,01 nm). Toutes se propagent à c=3×10⁸ m/s dans le vide. Seul le visible est perçu par l'œil. IR : chaleur. UV : bronzage/brûlures. X : radiologie. γ : noyaux radioactifs, traitement cancer. Fréquence = c/λ."},
  {"deck":"physique","id":"ph4n","chapitre":"Optique — Lumière et lentilles","q":"Comment fonctionne l'œil et ses défauts de vision ?","a":"L'œil est un système optique convergent. Le cristallin (lentille souple) accommode (change de courbure) pour former l'image nette sur la rétine. Myopie : globe trop long ou cristallin trop convergent → image avant la rétine → lunettes divergentes. Hypermétropie : globe trop court → image derrière → lunettes convergentes. Presbytie : vieillissement du cristallin (perd l'accommodation)."},
  {"deck":"physique","id":"ph4o","chapitre":"Optique — Lumière et lentilles","q":"Qu'est-ce que la diffraction et les interférences de la lumière ?","a":"Diffraction : une onde lumineuse se courbe en passant par une fente étroite (largeur ~ λ). Interférences : deux sources cohérentes créent des zones claires (interfèrent constructivement, Δ=kλ) et sombres (destructivement, Δ=(k+½)λ). Young (1801) : fentes de Young prouvent la nature ondulatoire de la lumière. Application : spectroscopie, holographie, anti-reflets."},

  {"deck":"physique","id":"ph5i","chapitre":"Électricité — Lois et circuits","q":"Qu'est-ce que la loi d'Ohm et comment s'applique-t-elle ?","a":"U = R·I. U (volt) = tension aux bornes de la résistance. R (ohm Ω) = résistance. I (ampère) = intensité. En série : R_tot = R₁+R₂+…, I identique dans tout le circuit. En parallèle : 1/R_tot = 1/R₁+1/R₂+…, U identique aux bornes de chaque résistance. La résistivité ρ : R = ρL/S (L = longueur, S = section du conducteur)."},
  {"deck":"physique","id":"ph5j","chapitre":"Électricité — Lois et circuits","q":"Qu'est-ce que la loi des nœuds et la loi des mailles ?","a":"Loi des nœuds (Kirchhoff courant) : la somme des courants entrants = somme des courants sortants en un nœud (conservation de la charge). Loi des mailles (Kirchhoff tension) : la somme algébrique des tensions dans une maille fermée = 0 (conservation de l'énergie). Ces deux lois permettent de résoudre n'importe quel circuit électrique."},
  {"deck":"physique","id":"ph5k","chapitre":"Électricité — Lois et circuits","q":"Comment fonctionne un condensateur dans un circuit ?","a":"Condensateur : deux plaques conductrices séparées par un isolant. Charge : q=CU (C en Farad, U tension). En régime transitoire RC : U_C(t) = E(1−e^(−t/τ)) avec τ=RC (constante de temps). Après 5τ : condensateur considéré chargé. Décharge : U_C(t) = U₀·e^(−t/τ). Bloque le courant continu, laisse passer l'alternatif."},
  {"deck":"physique","id":"ph5l","chapitre":"Électricité — Lois et circuits","q":"Comment fonctionne une bobine (inductance) dans un circuit ?","a":"Bobine : fil enroulé. Elle s'oppose aux variations de courant. En régime transitoire RL : I(t) = (E/R)(1−e^(−t/τ)) avec τ=L/R. Tension aux bornes : U_L = L·dI/dt. Énergie stockée : E_L = ½LI². Bobine ≈ court-circuit en régime permanent DC. Filtre passe-bas (laisse passer les basses fréquences)."},
  {"deck":"physique","id":"ph5m","chapitre":"Électricité — Lois et circuits","q":"Qu'est-ce que le courant alternatif sinusoïdal et ses grandeurs caractéristiques ?","a":"i(t) = I_max·sin(2πft+φ). I_max = amplitude (A), f = fréquence (Hz), T=1/f période (s), φ phase. Valeur efficace : I_eff = I_max/√2 (valeur équivalente en DC pour l'énergie dissipée). Le réseau 230V/50Hz : V_max=325V, T=20ms. Puissance : P = U_eff·I_eff·cos(φ) (facteur de puissance cos(φ))."},
  {"deck":"physique","id":"ph5n","chapitre":"Électricité — Lois et circuits","q":"Qu'est-ce qu'un oscillateur LC (circuit RLC) ?","a":"Circuit composé d'un condensateur C et d'une bobine L. Énergie oscille entre champ électrique (condensateur) et champ magnétique (bobine). Fréquence propre : f₀=1/(2π√(LC)). En présence de R : oscillations amorties (énergie dissipée). Résonance : si excitation à f₀ → amplitude maximale. Applications : tuner de radio, filtre passe-bande."},
  {"deck":"physique","id":"ph5o","chapitre":"Électricité — Lois et circuits","q":"Comment fonctionne un circuit logique et les portes logiques ?","a":"Porte ET (AND) : sortie 1 si et seulement si les deux entrées sont 1. Porte OU (OR) : sortie 1 si au moins une entrée est 1. Porte NON (NOT) : inverse l'entrée. NAND, NOR, XOR sont des combinaisons. Table de vérité : liste toutes les combinaisons d'entrées et la sortie correspondante. Tout ordinateur est construit à partir de milliards de ces portes logiques."},

  {"deck":"physique","id":"ph6i","chapitre":"Thermochimie et cinétique","q":"Qu'est-ce que l'enthalpie de réaction ΔrH et comment l'interpréter ?","a":"ΔrH = H_produits − H_réactifs. Unité : kJ/mol. ΔrH < 0 : réaction exothermique (libère de la chaleur, produits plus stables). ΔrH > 0 : endothermique (absorbe de la chaleur). Calculer via la loi de Hess : ΔrH = Σ ΔfH(produits) − Σ ΔfH(réactifs). Les ΔfH des corps simples à l'état standard = 0."},
  {"deck":"physique","id":"ph6j","chapitre":"Thermochimie et cinétique","q":"Qu'est-ce que la loi d'Arrhenius et l'énergie d'activation ?","a":"La vitesse d'une réaction augmente avec la température : k = A·e^(−Ea/RT). Ea = énergie d'activation (kJ/mol), R = 8,314 J/(mol·K), T en kelvin. Plus Ea est grande, plus la réaction est lente. Un catalyseur diminue Ea → accélère la réaction. Règle empirique : la vitesse double tous les 10°C (approx.). Représentation graphique : ln(k) vs 1/T = droite de pente −Ea/R."},
  {"deck":"physique","id":"ph6k","chapitre":"Thermochimie et cinétique","q":"Comment suit-on l'avancement d'une réaction cinétiquement ?","a":"Tableau d'avancement : quantités de matière initiales → état à l'avancement x → état final. Taux d'avancement τ = x_final/x_max. Pour les réactions limitées (équilibre) : τ<1. Pour les réactions quasi-totales : τ≈1. Suivi expérimental : spectrophotométrie (couleur), conductimétrie (ions), pH-métrie, prise d'aliquotes titrées."},
  {"deck":"physique","id":"ph6l","chapitre":"Thermochimie et cinétique","q":"Qu'est-ce qu'un catalyseur et comment agit-il ?","a":"Substance qui accélère une réaction sans être consommée et sans modifier l'état d'équilibre. Mécanismes : catalyse homogène (même phase, ex : H⁺ en solution), hétérogène (surface, ex : pot catalytique Pt/Pd), enzymatique (biologique, active à T°/pH précis). Le catalyseur fournit une autre voie de réaction avec Ea plus faible → plus de chocs efficaces → réaction plus rapide."},
  {"deck":"physique","id":"ph6m","chapitre":"Thermochimie et cinétique","q":"Qu'est-ce que l'ordre d'une réaction et comment le déterminer ?","a":"Pour aA + bB → produits : v = k·[A]ᵅ·[B]ᵝ. α et β sont les ordres partiels (déterminés expérimentalement, pas les coefficients stœchiométriques). Ordre total n = α+β. Ordre 1 : [A](t) = [A]₀·e^(−kt), t₁/₂ = ln(2)/k. Ordre 2 : 1/[A](t) = 1/[A]₀ + kt. Méthode dégagée : varier [A] et mesurer l'effet sur v."},
  {"deck":"physique","id":"ph6n","chapitre":"Thermochimie et cinétique","q":"Qu'est-ce que la constante d'équilibre K et le principe de Le Chatelier ?","a":"À l'équilibre : K = [produits]^stœchio / [réactifs]^stœchio. Principe de Le Chatelier : si on perturbe un équilibre (T, P, concentration), l'équilibre se déplace pour s'opposer à la perturbation. Ex : augmenter [réactif] → équilibre se déplace vers les produits. Augmenter T pour réaction endothermique → K augmente. Applications : synthèse de NH₃ (Haber-Bosch)."},
  {"deck":"physique","id":"ph6o","chapitre":"Thermochimie et cinétique","q":"Qu'est-ce que l'énergie interne et le premier principe de la thermodynamique ?","a":"ΔU = Q + W. ΔU = variation d'énergie interne, Q = chaleur reçue, W = travail reçu. Le 1er principe : l'énergie totale d'un système isolé est conservée. À pression constante : ΔH = Q_p (chaleur mesurée par calorimétrie). En chimie, on travaille souvent à pression constante → on mesure ΔrH. Applications : calorimétrie, moteurs thermiques."},

  {"deck":"physique","id":"ph7i","chapitre":"Chimie des solutions — Acides et Bases","q":"Comment calculer le pH d'un acide faible (monoacide faible) ?","a":"HA ⇌ H⁺ + A⁻. Ka = [H⁺][A⁻]/[HA]. Si α << 1 (taux de dissociation faible) : [H⁺] ≈ √(Ka·C). pH = ½(pKa − log C). Vérifier que α = [H⁺]/C < 5% pour valider l'approximation. Ex : CH₃COOH, pKa=4,75, C=0,1 mol/L → [H⁺] = √(10^(−4,75)×0,1) ≈ 1,3×10⁻³ → pH ≈ 2,9."},
  {"deck":"physique","id":"ph7j","chapitre":"Chimie des solutions — Acides et Bases","q":"Qu'est-ce qu'une solution tampon et comment la préparer ?","a":"Solution résistant aux variations de pH lors d'ajout d'acide ou de base. Contient un couple acide faible/base faible conjuguée (pH ≈ pKa quand [HA]=[A⁻]). Ex : CH₃COOH/CH₃COO⁻ (tampon acétate). Henderson-Hasselbalch : pH = pKa + log([A⁻]/[HA]). Rôle biologique : sang tamponné à pH 7,4 par le couple H₂CO₃/HCO₃⁻ (pKa=6,1 + système respiratoire)."},
  {"deck":"physique","id":"ph7k","chapitre":"Chimie des solutions — Acides et Bases","q":"Comment réalise-t-on un dosage acide-base par conductimétrie ?","a":"Mesurer la conductance σ de la solution en fonction du volume de titrant ajouté. La conductance change selon les ions présents. Au point d'équivalence : changement de pente brutal (les ions réactifs sont éliminés, remplacés par d'autres). Méthode précise, sans indicateur coloré, utilisable même pour des solutions colorées ou troubles. Point d'équivalence = intersection des deux droites."},
  {"deck":"physique","id":"ph7l","chapitre":"Chimie des solutions — Acides et Bases","q":"Qu'est-ce que l'hydrolyse des sels et comment prédire le pH d'une solution saline ?","a":"Sel d'acide fort + base forte (ex : NaCl) → solution neutre. Sel d'acide faible + base forte (ex : CH₃COONa) → hydrolyse basique (A⁻ + H₂O ⇌ HA + OH⁻) → pH > 7. Sel d'acide fort + base faible (ex : NH₄Cl) → hydrolyse acide (NH₄⁺ ⇌ NH₃ + H⁺) → pH < 7. Sel d'acide faible + base faible → pH selon Ka vs Kb."},
  {"deck":"physique","id":"ph7m","chapitre":"Chimie des solutions — Acides et Bases","q":"Qu'est-ce que la force d'un acide ou d'une base et les couples associés ?","a":"Acide fort (Ka très grand, pKa << 0) : dissociation totale en solution aqueuse. Ex : HCl, H₂SO₄, HNO₃. Base forte : OH⁻ total. Ex : NaOH, KOH. Acide faible : dissociation partielle. pKa intermédiaire. Ex : CH₃COOH (pKa=4,75), H₂CO₃ (pKa₁=6,4), NH₄⁺ (pKa=9,2). Couple : HA/A⁻. Force acide ↑ = force base conjuguée ↓."},
  {"deck":"physique","id":"ph7n","chapitre":"Chimie des solutions — Acides et Bases","q":"Comment interpréter une courbe de titrage pH-métrique ?","a":"Verser la base (ou acide) titrant progressivement dans l'acide (ou base) à titrer. La courbe pH=f(V_versé) présente : zone tampon avant l'équivalence (pH ≈ pKa à la demi-équivalence), saut de pH brutal au point d'équivalence, plateau après. Point d'équivalence : dérivée dpH/dV maximale, ou méthode des tangentes. Choisir indicateur dont virage pH est au niveau du saut."},
  {"deck":"physique","id":"ph7o","chapitre":"Chimie des solutions — Acides et Bases","q":"Qu'est-ce que la solubilité et le produit de solubilité Ks ?","a":"Ks = [M^n+][X^m-]^m pour MX_m → M^n+ + mX^m-. Ks petit → peu soluble. Ex : AgCl : Ks=1,8×10⁻¹⁰ (très peu soluble). Solubilité s : [M^n+]=s, [X^m-]=ms → Ks=(ms)^m·s. Effet d'ion commun : ajouter X^m- → précipitation de M. Conditions de précipitation : Q > Ks. Application : eau potable, traitement des eaux."},

  {"deck":"physique","id":"ph8i","chapitre":"Chimie organique","q":"Qu'est-ce que l'isomérie de constitution (isomérie de chaîne et de position) ?","a":"Isomères de constitution : même formule brute, liaisons différentes. Isomérie de chaîne : la chaîne carbonée est différente (linéaire vs ramifiée). Ex : butane C₄H₁₀ et isobutane (méthylpropane). Isomérie de position : le groupe fonctionnel est sur des carbones différents. Ex : propan-1-ol vs propan-2-ol. Isomérie de fonction : groupes fonctionnels différents. Ex : éthanol vs éther diméthylique."},
  {"deck":"physique","id":"ph8j","chapitre":"Chimie organique","q":"Qu'est-ce que la stéréoisomérie (Z/E et chiralité) ?","a":"Z/E (géométrique) : autour d'une double liaison C=C, si les groupes prioritaires sont du même côté → Z (zusammen). Côtés opposés → E (entgegen). Chiralité : carbone asymétrique (4 substituants différents) → 2 énantiomères (images miroir non superposables). Les énantiomères ont les mêmes propriétés physiques/chimiques mais peuvent avoir des effets biologiques opposés (ex : thalidomide)."},
  {"deck":"physique","id":"ph8k","chapitre":"Chimie organique","q":"Comment réaliser une synthèse organique à plusieurs étapes ?","a":"1) Analyser la molécule cible (groupes fonctionnels, chaîne). 2) Rétrosynthèse : identifier des précurseurs accessibles. 3) Choisir les réactions appropriées (substitution, addition, élimination, oxydation, réduction). 4) Optimiser les conditions (solvant, température, catalyseur). 5) Purifier le produit (recristallisation, distillation, chromatographie). 6) Caractériser (IR, RMN, SM)."},
  {"deck":"physique","id":"ph8l","chapitre":"Chimie organique","q":"Qu'est-ce qu'une réaction d'addition électrophile sur les alcènes ?","a":"La double liaison C=C est riche en électrons (π) → attirée par les électrophiles. Ex : addition de HBr sur propène : H⁺ (électrophile) s'attache au carbone le moins substitué (règle de Markovnikov), Br⁻ (nucléophile) sur le carbone le plus substitué → 2-bromopropane. L'intermédiaire est un carbocation. Addition d'eau (hydratation) en milieu acide suit la même règle."},
  {"deck":"physique","id":"ph8m","chapitre":"Chimie organique","q":"Qu'est-ce qu'une réaction de substitution nucléophile (SN) ?","a":"Un nucléophile (Nu⁻, possède doublet libre) remplace un groupe partant (LG, halogène) sur un carbone sp³. SN2 : attaque de derrière → inversion de configuration (Walden), cinétique 2e ordre. SN1 : formation d'un carbocation stable → racémisation, cinétique 1er ordre (favorisée par carbone 3° et solvant polaire). Compétition avec élimination (E1/E2) selon T° et base."},
  {"deck":"physique","id":"ph8n","chapitre":"Chimie organique","q":"Qu'est-ce que la réaction d'estérification et ses conditions ?","a":"Acide carboxylique + alcool ⇌ ester + eau. Catalysée par H⁺ (H₂SO₄ ou HCl). Réaction lente, limitée (équilibre). τ_éq ≈ 67 % pour acide/alcool primaire. Pour améliorer le rendement : excès d'un réactif, éliminer l'eau (Dean-Stark), ou utiliser un dérivé activé (chlorure d'acyle → réaction totale et rapide). Réaction inverse : hydrolyse ester."},
  {"deck":"physique","id":"ph8o","chapitre":"Chimie organique","q":"Quelles sont les techniques de caractérisation en chimie organique (IR, RMN) ?","a":"IR : vibrations de liaisons. Bandes caractéristiques : OH large (3200-3600), C=O (1700-1750), NH (3300-3500), C-H (2800-3000). Permet d'identifier les groupes fonctionnels. RMN ¹H : environnement des protons. Déplacement chimique δ (ppm) révèle le type de proton. Multiplicité : couplage avec les protons voisins (règle n+1). Intégration : nombre de protons. Ensemble IR+RMN → structure complète."},
]

# ═══════════════════════════════════════════════════════════════════════
# Injection
# ═══════════════════════════════════════════════════════════════════════
HTML_PATH = '/Users/stagiaire/flashcards/mobile.html'
OPEN_TAG  = '<script type="application/json" id="q-data">'
CLOSE_TAG = '</script>'

with open(HTML_PATH, encoding='utf-8') as f:
    html = f.read()

s = html.find(OPEN_TAG)
assert s != -1, 'q-data block not found'
e = html.find(CLOSE_TAG, s + len(OPEN_TAG))

data = json.loads(html[s + len(OPEN_TAG):e])

added = 0
for card in EXTRA:
    deck_id = card.pop('deck')
    deck = next((d for d in data['decks'] if d['id'] == deck_id), None)
    if deck is None:
        print(f'  ⚠ deck {deck_id} not found')
        continue
    existing_ids = {c['id'] for c in deck['cards']}
    if card['id'] not in existing_ids:
        deck['cards'].append(card)
        added += 1

new_json = json.dumps(data, ensure_ascii=False, indent=2)
html = html[:s + len(OPEN_TAG)] + '\n' + new_json + '\n' + html[e:]

with open(HTML_PATH, 'w', encoding='utf-8') as f:
    f.write(html)

print(f'Done — {added} cartes ajoutées')
for d in data['decks']:
    name = d['name']
    n = len(d['cards'])
    emoji = d['emoji']
    print(f'  {emoji} {name}: {n} cartes')
